# -*- coding: utf-8 -*-
"""Football_players_Analytics_performance (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1emeEWVxEgVmGeaENANonPzQbBc32YGFQ

# ⚽ Football Players Analytics Performance

> **AI-powered match analysis** using YOLOv8 and YOLOv22 object detection + KMeans jersey classification.

---

## 📋 Notebook Overview

| Cell | Purpose |
|------|--------|
| **Cell 1** | Install dependencies (run once per session) |
| **Cell 2** | Configure paths, team names & parameters |
| **Cell 3** | Run full AI analysis pipeline |
| **Cell 4** | Preview annotated video + green download button |
| **Cell 5** | Generate interactive web dashboard (HTML) |
| **Cell 6** | Download all output files to your computer |
| **Cell 7** | Deploy dashboard to Hugging Face Spaces |

---
> Full match (~5400 frames) takes **15-40 min** on GPU.

#Cell 1 — Install Dependencies
"""

!pip install ultralytics scikit-learn opencv-python-headless -q

import cv2, sklearn, ultralytics
print('✅ OpenCV      ', cv2.__version__)
print('✅ scikit-learn', sklearn.__version__)
print('✅ ultralytics ', ultralytics.__version__)
print('All packages ready')

"""## ⚙️ Cell 2 — Configure ← **Edit this cell**
Change `VIDEO_IN` to your video path and `TEAM_NAMES` to your team names.
"""

import os

DATASET_ZIP  = '/content/football-players-detection.v1i.yolov8 (1).zip'
DATASET_DIR  = '/content/football_dataset'
VIDEO_IN     = '/content/WhatsApp Video 2026-03-07 at 5.24.49 AM.mp4'
OUT_DIR      = '/content/soccer_output'
TEAM_NAMES   = ['Team 1', 'Team 2']   # team names
MAX_FRAMES   = 0   # 0 = full video  |  150 = quick 5-second test


os.makedirs(OUT_DIR, exist_ok=True)
VIDEO_OUT = f'{OUT_DIR}/overlay.mp4'
HTML_OUT  = f'{OUT_DIR}/match_report.html'
CSV_PLAY  = f'{OUT_DIR}/player_stats.csv'
CSV_PASS  = f'{OUT_DIR}/pass_events.csv'
HEAT0 = f'{OUT_DIR}/heatmap_team1.png'
HEAT1 = f'{OUT_DIR}/heatmap_team2.png'
PNET0 = f'{OUT_DIR}/passnet_team1.png'
PNET1 = f'{OUT_DIR}/passnet_team2.png'

print(f'   Config saved')
print(f'   Video  : {VIDEO_IN}')
print(f'   Teams  : {TEAM_NAMES[0]} vs {TEAM_NAMES[1]}')
print(f'   Output : {OUT_DIR}')
print(f'   Frames : {"All" if MAX_FRAMES==0 else MAX_FRAMES}')

"""## 🤖 Cell 3 — Run Full Analysis
**Runs automatically from start to finish:**
- Phase 1: Scan 60 frames, collect 400+ jersey samples, fit KMeans on HSV hue → team colors locked
- Phase 2: Process every frame — detect players + ball, track, classify teams, count passes, measure possession
- Phase 3: Generate heatmaps, pass networks, HTML report with embedded CSV downloads

Progress prints every 60 frames. Full match (~5400 frames) takes 15–40 minutes depending on GPU.
"""

import os, cv2, numpy as np, math, time, zipfile, csv
from dataclasses import dataclass, field
from collections import deque
from typing import Dict, List, Optional, Tuple

try:
    from sklearn.cluster import KMeans
    SKLEARN = True
except ImportError:
    SKLEARN = False
from ultralytics import YOLO

HUD_WIDTH   = 290

os.makedirs(OUT_DIR, exist_ok=True)
VIDEO_OUT = f"{OUT_DIR}/overlay.mp4"
HTML_OUT  = f"{OUT_DIR}/match_report.html"
CSV_PLAY  = f"{OUT_DIR}/player_stats.csv"
CSV_PASS  = f"{OUT_DIR}/pass_events.csv"
HEAT0     = f"{OUT_DIR}/heatmap_team1.png"
HEAT1     = f"{OUT_DIR}/heatmap_team2.png"
PNET0     = f"{OUT_DIR}/passnet_team1.png"
PNET1     = f"{OUT_DIR}/passnet_team2.png"

# ─────────────────────────────────────────────────
#  TUNING
# ─────────────────────────────────────────────────
CONF_THRESH      = 0.35
PERSON_CLS       = 0
BALL_CLS         = 32
POSS_RADIUS      = 110
POSS_SMOOTH_WIN  = 8
MIN_HOLD_FRAMES  = 4
PASS_COOLDOWN    = 10
MAX_PASS_M       = 50.0
MIN_PASS_M       = 1.2
PITCH_W_M        = 105.0
SPRINT_KMH       = 25.0
HI_KMH           = 15.0

PITCH_TOP    = 0.12
PITCH_BOT    = 0.78
PITCH_LEFT   = 0.02
PITCH_RIGHT  = 0.98

MIN_BOX_H_FRAC = 0.06
MAX_BOX_W_FRAC = 0.18
MIN_BOX_AREA   = 600

# ─────────────────────────────────────────────────
#  COLORS  (BGR)
# ─────────────────────────────────────────────────
TC = {
    0: (80, 210,  80),
    1: (30, 140, 255),
}
WHITE  = (255, 255, 255)
BLACK  = (0,   0,   0)
YELLOW = (0,  230, 230)
DARK_P = (18,  18,  24)
G_TRI  = (0,  200,  60)
R_TRI  = (30,  30, 220)

ZONE_NAMES = [
    ["Def-Left","Def-Ctr","Def-Right"],
    ["Mid-Left","Mid-Ctr","Mid-Right"],
    ["Att-Left","Att-Ctr","Att-Right"],
]


# ════════════════════════════════════════════════
#  PITCH ROI DETECTOR
# ════════════════════════════════════════════════
class PitchROI:
    def __init__(self, update_interval: int = 30):
        self.interval   = update_interval
        self.roi        = None
        self._last_fn   = -999

    def update(self, frame: np.ndarray, fn: int) -> Tuple[int,int,int,int]:
        if fn - self._last_fn < self.interval and self.roi is not None:
            return self.roi
        H, W = frame.shape[:2]
        hsv  = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
        lower = np.array([28,  40,  40])
        upper = np.array([88, 255, 210])
        mask  = cv2.inRange(hsv, lower, upper)
        k     = cv2.getStructuringElement(cv2.MORPH_RECT, (20, 20))
        mask  = cv2.morphologyEx(mask, cv2.MORPH_OPEN,  k)
        mask  = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, k)
        cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if cnts:
            largest = max(cnts, key=cv2.contourArea)
            if cv2.contourArea(largest) > W * H * 0.08:
                rx, ry, rw, rh = cv2.boundingRect(largest)
                shrink_x = int(rw * 0.03)
                shrink_y = int(rh * 0.03)
                rx1 = max(0, rx + shrink_x)
                ry1 = max(0, ry + shrink_y)
                rx2 = min(W, rx + rw - shrink_x)
                ry2 = min(H, ry + rh - shrink_y)
                rx1 = max(rx1, int(W * PITCH_LEFT))
                ry1 = max(ry1, int(H * PITCH_TOP))
                rx2 = min(rx2, int(W * PITCH_RIGHT))
                ry2 = min(ry2, int(H * PITCH_BOT))
                self.roi      = (rx1, ry1, rx2, ry2)
                self._last_fn = fn
                return self.roi
        self.roi = (int(W*PITCH_LEFT), int(H*PITCH_TOP),
                    int(W*PITCH_RIGHT), int(H*PITCH_BOT))
        self._last_fn = fn
        return self.roi

    def inside(self, cx, cy, fn, frame):
        roi = self.update(frame, fn)
        x1, y1, x2, y2 = roi
        return x1 <= cx <= x2 and y1 <= cy <= y2


# ════════════════════════════════════════════════
#  JERSEY CLASSIFIER  — KMeans on HSV hue
# ════════════════════════════════════════════════
class JerseyClassifier:
    def __init__(self):
        self.fitted  = False
        self.centers = None
        self.km      = None

    def jersey_hsv(self, frame: np.ndarray, bbox) -> Optional[np.ndarray]:
        x1, y1, x2, y2 = map(int, bbox)
        jy1 = y1 + max(1, int((y2-y1)*0.10))
        jy2 = y1 + max(2, int((y2-y1)*0.45))
        crop = frame[max(0,jy1):jy2, max(0,x1):x2]
        if crop.size == 0 or crop.shape[0] < 3 or crop.shape[1] < 3:
            return None
        sm   = cv2.resize(crop, (20, 20))
        hsv  = cv2.cvtColor(sm, cv2.COLOR_BGR2HSV)
        msk  = ((hsv[:,:,2] > 50) & (hsv[:,:,2] < 230) & (hsv[:,:,1] > 30))
        flat = hsv.reshape(-1, 3).astype(float)
        if msk.sum() < 10:
            return None
        good = flat[msk.flatten()]
        return good.mean(axis=0)

    def jersey_color(self, frame: np.ndarray, bbox) -> np.ndarray:
        x1, y1, x2, y2 = map(int, bbox)
        jy1 = y1 + max(1, int((y2-y1)*0.10))
        jy2 = y1 + max(2, int((y2-y1)*0.45))
        crop = frame[max(0,jy1):jy2, max(0,x1):x2]
        if crop.size == 0:
            return np.array([128, 128, 128.0])
        sm   = cv2.resize(crop, (16, 16))
        hsv  = cv2.cvtColor(sm, cv2.COLOR_BGR2HSV)
        msk  = ((hsv[:,:,2] > 50) & (hsv[:,:,2] < 230) & (hsv[:,:,1] > 30))
        px   = sm.reshape(-1, 3).astype(float)
        if msk.sum() > 8:
            px = px[msk.flatten()]
        return px.mean(axis=0)

    def fit(self, hsv_samples: list, bgr_samples: list):
        if len(hsv_samples) < 20:
            print(f"[WARN] Only {len(hsv_samples)} samples — classifier unreliable")
            return
        arr = np.array(hsv_samples)
        hs  = arr[:, :2].copy()
        hs[:, 0] /= 180.0
        hs[:, 1] /= 255.0
        from sklearn.cluster import KMeans
        km = KMeans(n_clusters=2, random_state=42, n_init=20, max_iter=500)
        km.fit(hs)
        self.km = km
        labels  = km.labels_
        bgr_arr = np.array(bgr_samples)
        self.centers = np.array([
            bgr_arr[labels == 0].mean(axis=0),
            bgr_arr[labels == 1].mean(axis=0),
        ])
        self.fitted = True
        self.clus_to_team = {0: 0, 1: 1}
        sz0 = (labels == 0).sum()
        sz1 = (labels == 1).sum()
        print(f"  KMeans fitted: cluster0={sz0}  BGR≈{self.centers[0].astype(int)}")
        print(f"                 cluster1={sz1}  BGR≈{self.centers[1].astype(int)}")

    def predict(self, hsv_color: Optional[np.ndarray], cx: float, W: int) -> int:
        if not self.fitted or self.km is None or hsv_color is None:
            return 0 if cx < W * 0.5 else 1
        hs  = np.array([[hsv_color[0]/180.0, hsv_color[1]/255.0]])
        raw = int(self.km.predict(hs)[0])
        return self.clus_to_team.get(raw, raw)

    def update_color_memory(self, color: np.ndarray, team: int):
        pass  # no longer needed


# ════════════════════════════════════════════════
#  DATA CLASSES
# ════════════════════════════════════════════════
@dataclass
class PlayerStats:
    pid:int; team:int
    total_dist:float=0.0; top_speed:float=0.0; avg_speed:float=0.0
    sprint_cnt:int=0; sprint_dist:float=0.0; hi_dist:float=0.0
    passes_made:int=0; passes_recv:int=0; poss_frames:int=0
    zone_counts:List[int]=field(default_factory=lambda:[0]*9)
    speed_hist:List[float]=field(default_factory=list)
    positions:List[Tuple]=field(default_factory=list)

    def tick(self, spd, dist):
        self.total_dist+=dist; self.speed_hist.append(round(spd,2))
        if spd>self.top_speed: self.top_speed=spd
        self.avg_speed=sum(self.speed_hist)/len(self.speed_hist)
        if spd>=SPRINT_KMH:
            self.sprint_dist+=dist
            if len(self.speed_hist)<2 or self.speed_hist[-2]<SPRINT_KMH:
                self.sprint_cnt+=1
        if spd>=HI_KMH: self.hi_dist+=dist

    def zone_idx(self,cx,cy,W,H):
        return min(2,int(cy/H*3))*3+min(2,int(cx/W*3))


@dataclass
class Player:
    pid:int; team:int
    cx:float; cy:float; feet_y:float
    speed:float=0.0; dist:float=0.0
    bbox:tuple=(0,0,0,0); missing:int=0
    stats:PlayerStats=field(default_factory=lambda:PlayerStats(0,0))
    def __post_init__(self): self.stats=PlayerStats(self.pid,self.team)


@dataclass
class PassEvent:
    frame:int; from_pid:int; to_pid:int; team:int
    dist_m:float; from_xy:Tuple; to_xy:Tuple


# ════════════════════════════════════════════════
#  PLAYER TRACKER
# ════════════════════════════════════════════════
class PlayerTracker:
    def __init__(self):
        self.players:Dict[int,Player]={}; self._nid=1

    def update(self, dets, fps, mpp, clf, frame, W, H):
        unmatched=list(range(len(dets))); matched=set(); pairs=[]
        for di,(cx,cy,fy,xyxy,bbox) in enumerate(dets):
            for pid,p in self.players.items():
                d=math.hypot(cx-p.cx,cy-p.cy)
                if d<85: pairs.append((d,di,pid))
        pairs.sort()
        for d,di,pid in pairs:
            if di not in unmatched or pid in matched: continue
            cx,cy,fy,xyxy,bbox=dets[di]
            p=self.players[pid]
            pxm=math.hypot(cx-p.cx,cy-p.cy)
            spd=min(pxm*fps*mpp*3.6,42.0); dist=pxm*mpp
            p.cx,p.cy,p.feet_y=cx,cy,fy; p.bbox=bbox
            p.speed=round(spd,2); p.dist=round(p.dist+dist,2)
            hsv_col = clf.jersey_hsv(frame, xyxy)
            p.team  = clf.predict(hsv_col, cx, W)
            p.missing=0
            p.stats.tick(spd,dist)
            p.stats.positions.append((int(cx),int(cy)))
            p.stats.zone_counts[p.stats.zone_idx(cx,cy,W,H)]+=1
            matched.add(pid); unmatched.remove(di)
        for di in unmatched:
            cx,cy,fy,xyxy,bbox=dets[di]
            hsv_col = clf.jersey_hsv(frame, xyxy)
            t       = clf.predict(hsv_col, cx, W)
            p=Player(pid=self._nid,team=t,cx=cx,cy=cy,feet_y=fy,bbox=bbox)
            self.players[self._nid]=p; self._nid+=1
        for pid in list(self.players):
            if pid not in matched:
                self.players[pid].missing+=1
                if self.players[pid].missing>12:
                    del self.players[pid]
        return self.players


# ════════════════════════════════════════════════
#  PASS TRACKER
# ════════════════════════════════════════════════
class PassTracker:
    def __init__(self):
        self.raw={0:0,1:0,-1:0}; self.passes={0:0,1:0}
        self.events:List[PassEvent]=[]
        self.history=deque(maxlen=POSS_SMOOTH_WIN)
        self.holder_pid=-1; self.holder_team=-1
        self.hold_frames=0
        self.holder_recv_x=0.0; self.holder_recv_y=0.0
        self.cooldown=0; self.curr_team=-1
        self.last_ball=None; self.ball_lost_fr=0
        self.attempted=0; self.rej_hold=0
        self.rej_dist=0; self.rej_inter=0
        self.poss_log:List[int]=[]

    def update(self, ball_xy, players:Dict, mpp:float, fn:int):
        if self.cooldown>0: self.cooldown-=1
        if ball_xy is not None:
            self.last_ball=ball_xy; self.ball_lost_fr=0
        elif self.last_ball is not None and self.ball_lost_fr<20:
            ball_xy=self.last_ball; self.ball_lost_fr+=1
        else:
            ball_xy=None
        holder_pid=-1
        if ball_xy and players:
            bx,by=ball_xy
            best_pid,best_d=-1,float("inf")
            for pid,p in players.items():
                d=math.hypot(p.cx-bx,p.feet_y-by)
                if d<best_d: best_d,best_pid=d,pid
            if best_d<POSS_RADIUS and best_pid!=-1:
                holder_pid=best_pid
                ht=players[best_pid].team
                self.raw[ht]+=1
                players[best_pid].stats.poss_frames+=1
                is_new_holder=(self.holder_pid!=-1 and self.holder_pid!=holder_pid)
                if is_new_holder and self.cooldown==0:
                    self.attempted+=1
                    prev=players.get(self.holder_pid)
                    if not prev:
                        pass
                    elif self.hold_frames<MIN_HOLD_FRAMES:
                        self.rej_hold+=1
                    else:
                        passer_team=prev.team
                        recv_pid=-1; recv_d=float("inf")
                        for pid2,p2 in players.items():
                            if pid2==self.holder_pid: continue
                            if p2.team!=passer_team: continue
                            d2=math.hypot(p2.cx-bx,p2.feet_y-by)
                            if d2<recv_d: recv_d=d2; recv_pid=pid2
                        if recv_pid==-1 or recv_d>POSS_RADIUS*2.5:
                            self.rej_inter+=1
                        else:
                            curr=players.get(recv_pid)
                            if curr:
                                dx=curr.cx-self.holder_recv_x
                                dy=curr.feet_y-self.holder_recv_y
                                dm=math.hypot(dx,dy)*mpp
                                if dm<MIN_PASS_M or dm>MAX_PASS_M:
                                    self.rej_dist+=1
                                else:
                                    t=passer_team
                                    self.passes[t]+=1
                                    self.cooldown=PASS_COOLDOWN
                                    prev.stats.passes_made+=1
                                    curr.stats.passes_recv+=1
                                    self.events.append(PassEvent(
                                        frame=fn,from_pid=self.holder_pid,
                                        to_pid=recv_pid,team=t,dist_m=round(dm,2),
                                        from_xy=(int(self.holder_recv_x),int(self.holder_recv_y)),
                                        to_xy=(int(curr.cx),int(curr.feet_y))))
                if holder_pid==self.holder_pid:
                    self.hold_frames+=1
                else:
                    cp=players.get(holder_pid)
                    self.hold_frames=1
                    self.holder_recv_x=cp.cx if cp else bx
                    self.holder_recv_y=cp.feet_y if cp else by
                self.holder_pid=holder_pid; self.holder_team=ht
            else:
                self.raw[-1]+=1
                if self.ball_lost_fr>6: self.holder_pid=-1
        else:
            self.raw[-1]+=1; self.holder_pid=-1
        entry=players[holder_pid].team if holder_pid in players else -1
        self.history.append(entry); self.poss_log.append(entry)
        cnt={0:0,1:0,-1:0}
        for t in self.history: cnt[t]+=1
        self.curr_team=max(cnt,key=cnt.get)
        return holder_pid,self.curr_team

    def pct(self):
        total=max(1,self.raw[0]+self.raw[1])
        return {0:round(100*self.raw[0]/total,2),1:round(100*self.raw[1]/total,2)}

    def debug_str(self):
        return (f"T1:{self.passes[0]} T2:{self.passes[1]}  "
                f"[att:{self.attempted} ok:{len(self.events)} "
                f"rh:{self.rej_hold} rd:{self.rej_dist} ri:{self.rej_inter}]")


# ════════════════════════════════════════════════
#  DRAWING
# ════════════════════════════════════════════════
def draw_player(frame, p:Player, is_holder:bool):
    fx,fy=int(p.cx),int(p.feet_y)
    col=TC[p.team]; fs=cv2.FONT_HERSHEY_SIMPLEX
    if p.team==0:
        r=7
        if is_holder: cv2.circle(frame,(fx,fy),r+5,YELLOW,1,cv2.LINE_AA)
        cv2.circle(frame,(fx,fy),r,col,-1,cv2.LINE_AA)
        cv2.circle(frame,(fx,fy),r,WHITE,1,cv2.LINE_AA)
    else:
        d=8
        if is_holder:
            di=d+5
            hi=np.array([[fx,fy-di],[fx+di,fy],[fx,fy+di],[fx-di,fy]],np.int32)
            cv2.polylines(frame,[hi],True,YELLOW,1,cv2.LINE_AA)
        pts=np.array([[fx,fy-d],[fx+d,fy],[fx,fy+d],[fx-d,fy]],np.int32)
        cv2.fillPoly(frame,[pts],col)
        cv2.polylines(frame,[pts],True,WHITE,1,cv2.LINE_AA)
    s=str(p.pid)
    (tw,th),_=cv2.getTextSize(s,fs,0.26,1)
    pad=2; gap=7+2
    ly2=fy-gap; ly1=ly2-th-pad
    lx1=fx-tw//2-pad; lx2=fx+tw//2+pad
    cv2.rectangle(frame,(lx1,ly1),(lx2,ly2),col,-1)
    cv2.putText(frame,s,(lx1+pad,ly2-1),fs,0.26,WHITE,1,cv2.LINE_AA)
    if is_holder:
        ax=fx; ay=ly1-2
        cv2.drawContours(frame,[np.array([[ax-4,ay-5],[ax+4,ay-5],[ax,ay]],np.int32)],0,YELLOW,-1,cv2.LINE_AA)
    spd=f"{p.speed:.0f}"
    (sw,sh),_=cv2.getTextSize(spd,fs,0.22,1)
    sx=fx-sw//2; sy=fy+gap+sh
    cv2.rectangle(frame,(sx-1,sy-sh-1),(sx+sw+1,sy+1),(0,0,0),-1)
    cv2.putText(frame,spd,(sx,sy),fs,0.22,col,1,cv2.LINE_AA)


def draw_pitch_roi(frame, roi:Tuple, show:bool=False):
    if not show or roi is None: return
    x1,y1,x2,y2=roi
    cv2.rectangle(frame,(x1,y1),(x2,y2),(0,255,0),1)
    cv2.putText(frame,"PITCH ROI",(x1+4,y1+14),cv2.FONT_HERSHEY_SIMPLEX,0.4,(0,255,0),1)


def draw_hud(panel,ptracker,players,fn,fps):
    panel[:]=DARK_P; pw=panel.shape[1]
    def t(s,x,y,sc=0.40,col=WHITE,bold=False):
        cv2.putText(panel,s,(x,y),cv2.FONT_HERSHEY_DUPLEX if bold else cv2.FONT_HERSHEY_SIMPLEX,sc,col,1,cv2.LINE_AA)
    def hl(y,c=(55,55,68)): cv2.line(panel,(0,y),(pw,y),c,1)
    def bar(x,y,bw,frac,col,bh=7):
        cv2.rectangle(panel,(x,y),(x+bw,y+bh),(40,40,52),-1)
        cv2.rectangle(panel,(x,y),(x+max(2,int(bw*frac)),y+bh),col,-1)
    cv2.rectangle(panel,(0,0),(pw,32),(22,22,34),-1)
    t("SOCCER ANALYTICS PRO",6,14,0.43,WHITE,True)
    sec=int(fn/max(fps,1)); m,s=divmod(sec,60)
    t(f"{m:02d}:{s:02d}",pw-52,14,0.42,(160,160,160))
    y=36
    pct=ptracker.pct(); hl(y); y+=8
    t("BALL CONTROL",7,y+11,0.37,(140,140,155))
    t(f"{pct[0]:.1f}%",7,y+25,0.50,TC[0],True)
    t(f"{pct[1]:.1f}%",pw-50,y+25,0.50,TC[1],True)
    bw2=pw-16
    cv2.rectangle(panel,(8,y+30),(8+bw2,y+38),(40,40,52),-1)
    fa=max(3,int(bw2*pct[0]/100))
    cv2.rectangle(panel,(8,y+30),(8+fa,y+38),TC[0],-1)
    cv2.rectangle(panel,(8+fa,y+30),(8+bw2,y+38),TC[1],-1)
    y+=46
    hl(y); y+=8
    t("PASSES",7,y+11,0.42,(140,140,155),True); y+=18
    for i in(0,1):
        col=TC[i]
        if i==0:
            cv2.circle(panel,(14,y+11),7,col,-1,cv2.LINE_AA)
            cv2.circle(panel,(14,y+11),7,WHITE,1,cv2.LINE_AA)
        else:
            d=8; pts=np.array([[14,y+11-d],[14+d,y+11],[14,y+11+d],[14-d,y+11]],np.int32)
            cv2.fillPoly(panel,[pts],col); cv2.polylines(panel,[pts],True,WHITE,1,cv2.LINE_AA)
        t(str(ptracker.passes[i]),26,y+16,0.65,col,True)
        ps=str(ptracker.passes[i])
        (nw,_),_=cv2.getTextSize(ps,cv2.FONT_HERSHEY_DUPLEX,0.65,1)
        t(TEAM_NAMES[i],26+nw+8,y+16,0.40,WHITE)
        evs=[e for e in ptracker.events if e.team==i]
        avgd=round(sum(e.dist_m for e in evs)/max(len(evs),1),1)
        t(f"avg {avgd}m/pass",26+nw+8,y+30,0.32,(110,110,120))
        y+=38
    y+=2
    hl(y); y+=8
    t("TOP SPEED",7,y+11,0.37,(140,140,155))
    for i in(0,1):
        sp=[p.speed for p in players.values() if p.team==i]
        val=max(sp) if sp else 0.0
        bar(8,y+14+i*16,pw-16,min(val/40,1),TC[i],5)
        t(f"{TEAM_NAMES[i]}  {val:.1f}km/h",8,y+26+i*16,0.35,WHITE)
    y+=44
    hl(y); y+=8
    t("AVG SPEED",7,y+11,0.37,(140,140,155))
    for i in(0,1):
        sp=[p.speed for p in players.values() if p.team==i]
        avg=sum(sp)/max(len(sp),1)
        bar(8,y+14+i*16,pw-16,min(avg/18,1),TC[i],5)
        t(f"{TEAM_NAMES[i]}  {avg:.1f}km/h",8,y+26+i*16,0.35,WHITE)
    y+=44
    hl(y); y+=8
    t("TOP PASSERS",7,y+11,0.37,(140,140,155)); y+=17
    top=sorted(players.values(),key=lambda p:p.stats.passes_made,reverse=True)[:6]
    for p in top:
        col=TC[p.team]; cv2.circle(panel,(12,y+5),4,col,-1)
        t(f"#{p.pid:<3}  made:{p.stats.passes_made}  recv:{p.stats.passes_recv}",20,y+9,0.33,WHITE)
        y+=15
    y+=4
    hl(y); y+=8
    na=sum(1 for p in players.values() if p.team==0)
    nb=sum(1 for p in players.values() if p.team==1)
    t(f"On pitch:  T1:{na}   T2:{nb}",7,y+12,0.35,(160,160,160))
    y+=22
    hl(y); y+=8
    pname=TEAM_NAMES[ptracker.curr_team] if ptracker.curr_team in(0,1) else "Contested"
    pcol=TC.get(ptracker.curr_team,(130,130,130))
    t("POSSESSION:",7,y+12,0.36,(140,140,155))
    t(pname,108,y+12,0.40,pcol,True)
    y+=22
    hl(y); y+=8
    t("SPRINTS (>25km/h)",7,y+11,0.37,(140,140,155))
    for i in(0,1):
        sc=sum(p.stats.sprint_cnt for p in players.values() if p.team==i)
        cv2.circle(panel,(14,y+20+i*14),4,TC[i],-1)
        t(f"{TEAM_NAMES[i]}:  {sc}",24,y+24+i*14,0.34,WHITE)
    y+=36
    hl(y); y+=5
    t(f"passes {ptracker.debug_str()}",7,y+10,0.27,(60,60,80))


def draw_poss_panel(frame,ptracker):
    H,W=frame.shape[:2]; pct=ptracker.pct()
    pw,ph=300,52; px1=W-pw-10; py1=H-ph-10
    ov=frame.copy()
    cv2.rectangle(ov,(px1,py1),(px1+pw,py1+ph),(15,15,15),-1)
    cv2.addWeighted(ov,0.75,frame,0.25,0,frame)
    cv2.rectangle(frame,(px1,py1),(px1+pw,py1+ph),(60,60,70),1)
    fs=cv2.FONT_HERSHEY_SIMPLEX
    for i,(tid,col) in enumerate([(0,TC[0]),(1,TC[1])]):
        sy=py1+12+i*22; ix=px1+8+5; iy=sy+5
        if tid==0:
            cv2.circle(frame,(ix,iy),5,col,-1,cv2.LINE_AA)
            cv2.circle(frame,(ix,iy),5,WHITE,1,cv2.LINE_AA)
        else:
            d=6; pts=np.array([[ix,iy-d],[ix+d,iy],[ix,iy+d],[ix-d,iy]],np.int32)
            cv2.fillPoly(frame,[pts],col); cv2.polylines(frame,[pts],True,WHITE,1,cv2.LINE_AA)
        cv2.putText(frame,f"{TEAM_NAMES[tid]}  Ball Control: {pct[tid]:.1f}%",(px1+22,sy+9),fs,0.38,WHITE,1,cv2.LINE_AA)


def draw_timeline(frame,poss_log):
    H,W=frame.shape[:2]; bw,bh=W-20,6; bx,by=10,4
    cv2.rectangle(frame,(bx,by),(bx+bw,by+bh),(30,30,30),-1)
    if poss_log:
        seg=max(1,len(poss_log))
        for i,t in enumerate(poss_log):
            x=bx+int(i/seg*bw); w=max(1,int(bw/seg)+1)
            cv2.rectangle(frame,(x,by),(x+w,by+bh),TC.get(t,(40,40,40)),-1)
    cv2.rectangle(frame,(bx,by),(bx+bw,by+bh),(70,70,70),1)


# ════════════════════════════════════════════════
#  POST-MATCH OUTPUTS
# ════════════════════════════════════════════════
def make_heatmap(players,team,W,H,path):
    canvas=np.zeros((H,W,3),np.uint8)
    cv2.rectangle(canvas,(0,0),(W,H),(30,100,30),-1)
    mx,my=40,30
    cv2.rectangle(canvas,(mx,my),(W-mx,H-my),(255,255,255),2)
    cv2.line(canvas,(W//2,my),(W//2,H-my),(255,255,255),2)
    cv2.circle(canvas,(W//2,H//2),int(H*0.13),(255,255,255),2)
    heat=np.zeros((H,W),np.float32)
    for p in players.values():
        if p.team!=team: continue
        for (px2,py2) in p.stats.positions:
            y1,y2_=max(0,py2-70),min(H,py2+70)
            x1,x2_=max(0,px2-70),min(W,px2+70)
            Y,X=np.ogrid[y1:y2_,x1:x2_]
            heat[y1:y2_,x1:x2_]+=np.maximum(0,1-np.sqrt((X-px2)**2+(Y-py2)**2)/70)**2
    if heat.max()>0: heat=np.clip(heat/heat.max(),0,1)
    cm=cv2.applyColorMap((heat*255).astype(np.uint8),cv2.COLORMAP_JET)
    canvas=(canvas*(1-heat[:,:,np.newaxis]*0.7)+cm*heat[:,:,np.newaxis]*0.7).astype(np.uint8)
    cv2.putText(canvas,f"{TEAM_NAMES[team]} Heatmap",(mx+10,my+24),cv2.FONT_HERSHEY_DUPLEX,0.7,(255,255,255),1)
    cv2.imwrite(path,canvas); print(f"[OK]  Heatmap → {path}")


def make_passnet(players,events,team,W,H,path):
    canvas=np.zeros((H,W,3),np.uint8)
    cv2.rectangle(canvas,(0,0),(W,H),(25,80,25),-1)
    mx,my=40,30
    cv2.rectangle(canvas,(mx,my),(W-mx,H-my),(200,200,200),2)
    cv2.line(canvas,(W//2,my),(W//2,H-my),(200,200,200),2)
    pairs:Dict[tuple,int]={}
    for ev in events:
        if ev.team!=team: continue
        k=(min(ev.from_pid,ev.to_pid),max(ev.from_pid,ev.to_pid))
        pairs[k]=pairs.get(k,0)+1
    avg_pos={}
    for pid,p in players.items():
        if p.team==team and p.stats.positions:
            xs=[x for x,y in p.stats.positions]; ys=[y for x,y in p.stats.positions]
            avg_pos[pid]=(int(sum(xs)/len(xs)),int(sum(ys)/len(ys)))
    maxc=max(pairs.values()) if pairs else 1; col=TC[team]
    for (a,b),cnt in pairs.items():
        if a not in avg_pos or b not in avg_pos: continue
        cv2.line(canvas,avg_pos[a],avg_pos[b],col,max(1,int(cnt/maxc*6)),cv2.LINE_AA)
        mx2=(avg_pos[a][0]+avg_pos[b][0])//2; my2=(avg_pos[a][1]+avg_pos[b][1])//2
        cv2.putText(canvas,str(cnt),(mx2,my2),cv2.FONT_HERSHEY_SIMPLEX,0.32,WHITE,1)
    for pid,pos in avg_pos.items():
        p=players[pid]
        cv2.circle(canvas,pos,16,col,-1,cv2.LINE_AA); cv2.circle(canvas,pos,16,WHITE,1,cv2.LINE_AA)
        s=str(pid); (tw,th2),_=cv2.getTextSize(s,cv2.FONT_HERSHEY_DUPLEX,0.45,1)
        cv2.putText(canvas,s,(pos[0]-tw//2,pos[1]+th2//2),cv2.FONT_HERSHEY_DUPLEX,0.45,BLACK,1)
        cv2.putText(canvas,f"{p.stats.passes_made}p",(pos[0]-8,pos[1]+28),cv2.FONT_HERSHEY_SIMPLEX,0.28,(220,220,220),1)
    cv2.putText(canvas,f"{TEAM_NAMES[team]} Pass Network",(mx+10,my+24),cv2.FONT_HERSHEY_DUPLEX,0.7,WHITE,1)
    cv2.imwrite(path,canvas); print(f"[OK]  Pass network → {path}")


def export_csvs(players,ptracker):
    rows=[]
    for pid,p in sorted(players.items()):
        s=p.stats; zi=max(range(9),key=lambda i:s.zone_counts[i])
        rows.append({"player_id":pid,"role":TEAM_NAMES[p.team],
                     "total_dist_m":round(s.total_dist,2),"top_speed_kmh":round(s.top_speed,2),
                     "avg_speed_kmh":round(s.avg_speed,2),"sprint_count":s.sprint_cnt,
                     "sprint_dist_m":round(s.sprint_dist,2),"passes_made":s.passes_made,
                     "passes_received":s.passes_recv,"main_zone":ZONE_NAMES[zi//3][zi%3]})
    if rows:
        with open(CSV_PLAY,"w",newline="") as f:
            w=csv.DictWriter(f,fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)
        print(f"[OK]  Player CSV → {CSV_PLAY}")
    if ptracker.events:
        with open(CSV_PASS,"w",newline="") as f:
            w=csv.DictWriter(f,fieldnames=["frame","team","from","to","dist_m"]); w.writeheader()
            for ev in ptracker.events:
                w.writerow({"frame":ev.frame,"team":TEAM_NAMES[ev.team],"from":ev.from_pid,"to":ev.to_pid,"dist_m":ev.dist_m})
        print(f"[OK]  Pass CSV  → {CSV_PASS}")


def export_html(players,ptracker,dur,vname):
    import base64,io

    def img64(p):
        if not p or not os.path.exists(p): return ""
        ext=p.rsplit(".",1)[-1]; data=base64.b64encode(open(p,"rb").read()).decode()
        n=os.path.basename(p)
        return ('<figure style="margin:0"><img src="data:image/'+ext+';base64,'+data+'" '
                'style="width:100%;border-radius:10px;display:block">'
                '<figcaption style="font-size:.72rem;color:#555;text-align:center;margin-top:6px">'+n+'</figcaption></figure>')

    def make_player_csv():
        rows=["player_id,team,total_dist_m,top_speed_kmh,avg_speed_kmh,sprint_count,sprint_dist_m,passes_made,passes_received,main_zone"]
        for pid,p in sorted(players.items()):
            s=p.stats; zi=max(range(9),key=lambda i:s.zone_counts[i]); zn=ZONE_NAMES[zi//3][zi%3]
            rows.append(",".join(str(x) for x in [pid,TEAM_NAMES[p.team],round(s.total_dist,2),round(s.top_speed,2),round(s.avg_speed,2),s.sprint_cnt,round(s.sprint_dist,2),s.passes_made,s.passes_recv,zn]))
        return "\n".join(rows)+"\n"

    def make_pass_csv():
        rows=["frame,team,from_pid,to_pid,dist_m"]
        for ev in ptracker.events:
            rows.append(str(ev.frame)+","+TEAM_NAMES[ev.team]+","+str(ev.from_pid)+","+str(ev.to_pid)+","+str(ev.dist_m))
        return "\n".join(rows)+"\n"

    csv_pl=base64.b64encode(make_player_csv().encode()).decode()
    csv_pa=base64.b64encode(make_pass_csv().encode()).decode()

    pct=ptracker.pct(); mins=int(dur//60); sc=int(dur%60)
    C0="#3ddc84"; C1="#4db8ff"
    G0="linear-gradient(135deg,#1a3a28,#0d1f16)"; G1="linear-gradient(135deg,#162840,#0b1624)"
    p0w=max(2,int(pct[0])); p1w=max(2,100-p0w)
    tn0=TEAM_NAMES[0]; tn1=TEAM_NAMES[1]

    td={}
    for tid in(0,1):
        ps=[p for p in players.values() if p.team==tid]
        evs=[e for e in ptracker.events if e.team==tid]
        td[tid]={
            "n":len(ps),
            "dist":round(sum(p.stats.total_dist for p in ps),1),
            "top":round(max((p.stats.top_speed for p in ps),default=0),2),
            "avg":round(sum(p.stats.avg_speed for p in ps)/max(len(ps),1),2),
            "sprints":sum(p.stats.sprint_cnt for p in ps),
            "passes":ptracker.passes[tid],
            "avg_pd":round(sum(e.dist_m for e in evs)/max(len(evs),1),1),
            "hi_dist":round(sum(p.stats.hi_dist for p in ps),1),
        }

    def card(lbl,val,sub="",col="#fff"):
        return '<div class="card"><div class="cl">'+lbl+'</div><div class="cv" style="color:'+col+'">'+str(val)+'</div>'+(('<div class="cs">'+sub+'</div>') if sub else '')+'</div>'

    def prows(tid):
        cv=C0 if tid==0 else C1; out=""
        for p in sorted([p for p in players.values() if p.team==tid],key=lambda x:x.stats.total_dist,reverse=True):
            s=p.stats; zi=max(range(9),key=lambda i:s.zone_counts[i]); zn=ZONE_NAMES[zi//3][zi%3]
            sb=min(100,int(s.sprint_cnt*8)); spb=min(100,int(s.top_speed/40*100))
            out+=('<tr>'
                '<td><span class="pid" style="background:'+cv+'20;color:'+cv+';border:1px solid '+cv+'40">#'+str(p.pid)+'</span></td>'
                '<td>'+str(round(s.total_dist,1))+'m</td>'
                '<td><span style="color:'+cv+'">'+str(round(s.top_speed,1))+'</span></td>'
                '<td>'+str(round(s.avg_speed,1))+'km/h</td>'
                '<td>'+str(s.sprint_cnt)+'</td>'
                '<td><span class="badge" style="background:'+cv+'22;color:'+cv+'">'+str(s.passes_made)+'</span></td>'
                '<td><span class="badge" style="background:#ffffff11;color:#aaa">'+str(s.passes_recv)+'</span></td>'
                '<td style="color:#666;font-size:.7rem">'+zn+'</td>'
                '</tr>')
        return out

    plog=""
    for ev in ptracker.events[-80:]:
        ec=C0 if ev.team==0 else C1; tn=TEAM_NAMES[ev.team]
        plog+=('<tr><td style="color:#555">'+str(ev.frame)+'</td>'
               '<td><span class="badge" style="background:'+ec+'22;color:'+ec+'">'+tn+'</span></td>'
               '<td>#'+str(ev.from_pid)+' &#8594; #'+str(ev.to_pid)+'</td>'
               '<td style="color:#aaa">'+str(ev.dist_m)+'m</td></tr>')

    team_secs=""
    for tid in(0,1):
        bg=G0 if tid==0 else G1; cv=C0 if tid==0 else C1; tn=TEAM_NAMES[tid]
        team_secs+=('<div style="background:'+bg+';border-radius:16px;padding:24px 28px;margin-bottom:20px;border:1px solid rgba(255,255,255,0.06)">'
            '<div style="font-size:1.25rem;font-weight:700;margin-bottom:18px;display:flex;align-items:center;gap:10px">'
            '<div style="width:10px;height:10px;border-radius:50%;background:'+cv+'"></div>'
            '<span style="color:'+cv+'">'+tn+'</span></div>'
            '<div class="cards">'
            +card("Players",td[tid]["n"],col=cv)
            +card("Ball Control",str(pct[tid])+"% ","",cv)
            +card("Passes",td[tid]["passes"],"avg "+str(td[tid]["avg_pd"])+"m",cv)
            +card("Total Dist",str(td[tid]["dist"])+"m","",cv)
            +card("Top Speed",str(td[tid]["top"])+"km/h","",cv)
            +card("Avg Speed",str(td[tid]["avg"])+"km/h","",cv)
            +card("Sprints",td[tid]["sprints"],"",cv)
            +card("HI Dist",str(td[tid]["hi_dist"])+"m","",cv)
            +'</div>'
            '<table><thead><tr>'
            '<th>ID</th><th>Distance</th><th>Top Speed</th><th>Avg Speed</th>'
            '<th>Sprints</th><th>Made</th><th>Recv</th><th>Zone</th>'
            '</tr></thead><tbody>'+prows(tid)+'</tbody></table></div>')

    css=("*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}"
        ":root{--bg:#080b12;--bg1:#0d1120;--bg3:#161d2e;--border:rgba(255,255,255,0.06);--text:#e2e8f0;--muted:#64748b}"
        "body{font-family:'Inter',sans-serif;background:var(--bg);color:var(--text);line-height:1.6}"
        ".page{max-width:1140px;margin:0 auto;padding:32px 20px 80px}"
        ".hero{background:linear-gradient(135deg,#0d1120,#0a1628,#0d1120);border:1px solid var(--border);border-radius:20px;padding:40px 48px;margin-bottom:28px}"
        ".hero-grid{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:24px}"
        ".tn{font-size:1.6rem;font-weight:800}"
        ".score-box{text-align:center}.score-num{font-size:3.5rem;font-weight:800;color:#fff;letter-spacing:6px}"
        ".score-sub{font-size:.8rem;color:var(--muted);margin-top:4px;text-transform:uppercase}"
        ".sec{background:var(--bg1);border:1px solid var(--border);border-radius:16px;padding:24px 28px;margin-bottom:20px}"
        ".sec-title{font-size:.7rem;font-weight:600;color:var(--muted);text-transform:uppercase;letter-spacing:1.5px;margin-bottom:16px}"
        ".poss-labels{display:flex;justify-content:space-between;margin-bottom:8px}"
        ".poss-label{font-size:.9rem;font-weight:600}"
        ".cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:10px;margin-bottom:20px}"
        ".card{background:rgba(0,0,0,0.3);border-radius:12px;padding:14px 16px;border:1px solid var(--border)}"
        ".cl{font-size:.6rem;color:var(--muted);text-transform:uppercase;letter-spacing:1px;margin-bottom:8px;font-weight:500}"
        ".cv{font-size:1.6rem;font-weight:700;line-height:1}.cs{font-size:.7rem;color:var(--muted);margin-top:4px}"
        "table{width:100%;border-collapse:collapse;font-size:.78rem}"
        "thead tr{background:rgba(0,0,0,0.3)}"
        "th{padding:10px 12px;text-align:left;color:var(--muted);font-size:.65rem;text-transform:uppercase;letter-spacing:1px;font-weight:500;border-bottom:1px solid var(--border)}"
        "td{padding:9px 12px;border-bottom:1px solid var(--border)}"
        "tr:last-child td{border-bottom:none}tr:hover td{background:rgba(255,255,255,0.02)}"
        ".pid{display:inline-block;padding:2px 8px;border-radius:6px;font-weight:600;font-size:.72rem}"
        ".badge{display:inline-block;padding:2px 8px;border-radius:6px;font-size:.72rem;font-weight:500}"
        ".g2{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:4px}"
        ".pass-log-sec{background:var(--bg1);border:1px solid var(--border);border-radius:16px;padding:24px 28px;margin-bottom:20px}"
        "footer{text-align:center;color:var(--muted);font-size:.72rem;margin-top:40px;opacity:.5}"
        ".dl-btn{display:inline-flex;align-items:center;gap:8px;padding:10px 20px;border-radius:10px;"
        "font-size:.82rem;font-weight:600;text-decoration:none;border:1px solid var(--border);"
        "background:rgba(255,255,255,0.04);color:var(--text)}"
        ".dl-row{display:flex;flex-wrap:wrap;gap:12px;margin-top:4px}")

    html=('<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">'
          '<title>Match Report</title>'
          '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">'
          '<style>'+css+'</style></head><body><div class="page">'
          '<div style="margin-bottom:24px">'
          '<h1 style="font-size:1.1rem;font-weight:600;color:var(--muted);letter-spacing:2px;text-transform:uppercase">&#9917; Match Report</h1>'
          '<p style="font-size:.8rem;color:#374151;margin-top:4px">'+vname+' &#183; '+str(mins).zfill(2)+':'+str(sc).zfill(2)+'</p></div>'
          '<div class="hero"><div class="hero-grid">'
          '<div class="tn" style="color:'+C0+'">'+tn0+'</div>'
          '<div class="score-box"><div class="score-num">'+str(td[0]["passes"])+' &#8212; '+str(td[1]["passes"])+'</div>'
          '<div class="score-sub">Passes &#183; '+str(mins).zfill(2)+':'+str(sc).zfill(2)+'</div></div>'
          '<div class="tn" style="color:'+C1+';text-align:right">'+tn1+'</div>'
          '</div></div>'
          '<div class="sec"><div class="sec-title">Ball Control</div>'
          '<div class="poss-labels">'
          '<span class="poss-label" style="color:'+C0+'">'+tn0+' '+str(pct[0])+'%</span>'
          '<span class="poss-label" style="color:'+C1+'">'+str(pct[1])+'% '+tn1+'</span></div>'
          '<div style="height:12px;border-radius:6px;display:flex;overflow:hidden;background:var(--bg3)">'
          '<div style="width:'+str(p0w)+'%;background:'+C0+';border-radius:6px 0 0 6px"></div>'
          '<div style="width:'+str(p1w)+'%;background:'+C1+';border-radius:0 6px 6px 0"></div>'
          '</div></div>'
          +team_secs+
          '<div class="sec"><div class="sec-title">Heatmaps</div>'
          '<div class="g2">'+img64(HEAT0)+img64(HEAT1)+'</div></div>'
          '<div class="sec"><div class="sec-title">Pass Networks</div>'
          '<div class="g2">'+img64(PNET0)+img64(PNET1)+'</div></div>'
          '<div class="pass-log-sec"><div class="sec-title">Pass Log &#8212; last 80</div>'
          '<table><thead><tr><th>Frame</th><th>Team</th><th>Pass</th><th>Dist</th></tr></thead>'
          '<tbody>'+plog+'</tbody></table></div>'
          '<div class="sec"><div class="sec-title">Download Data</div><div class="dl-row">'
          '<a href="data:text/csv;base64,'+csv_pl+'" download="player_stats.csv" class="dl-btn">&#128202; Player Stats CSV</a>'
          '<a href="data:text/csv;base64,'+csv_pa+'" download="pass_events.csv" class="dl-btn">&#128203; Pass Events CSV</a>'
          '</div><p style="font-size:.72rem;color:var(--muted);margin-top:12px">Click to download.</p></div>'
          '<footer>Soccer Analytics Pro &#183; '+vname+'</footer>'
          '</div></body></html>')

    with open(HTML_OUT,"w",encoding="utf-8") as f: f.write(html)
    print("[OK]  HTML Report -> "+HTML_OUT)


def learn_colors(video_path,clf,model,n_frames=60):
    cap=cv2.VideoCapture(video_path)
    tot=int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    W=int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    H=int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    idxs=np.linspace(0,min(tot-1,1500),n_frames,dtype=int)
    pitch_roi=PitchROI(); hsv_samples=[]; bgr_samples=[]
    for idx in idxs:
        cap.set(cv2.CAP_PROP_POS_FRAMES,int(idx))
        ret,frame=cap.read()
        if not ret: continue
        roi=pitch_roi.update(frame,int(idx)); rx1,ry1,rx2,ry2=roi
        res=model(frame,classes=[PERSON_CLS],conf=0.40,verbose=False)[0]
        for box in res.boxes:
            xy=box.xyxy[0].cpu().numpy(); x1,y1,x2,y2=map(int,xy); cx,cy=(x1+x2)/2,(y1+y2)/2
            if not (rx1<=cx<=rx2 and ry1<=cy<=ry2): continue
            if y2>ry2: continue
            bh,bw=y2-y1,x2-x1
            if bh<H*MIN_BOX_H_FRAC or bw>H*MAX_BOX_W_FRAC: continue
            if bh*bw<MIN_BOX_AREA or bw>bh*1.1: continue
            if float(box.conf[0])<0.40: continue
            hsv=clf.jersey_hsv(frame,xy); bgr=clf.jersey_color(frame,xy)
            if hsv is not None: hsv_samples.append(hsv); bgr_samples.append(bgr)
    cap.release()
    print(f"  Collected {len(hsv_samples)} jersey samples from {n_frames} frames")
    clf.fit(hsv_samples,bgr_samples)


# ════════════════════════════════════════════════
#  MAIN
# ════════════════════════════════════════════════
def run():
    os.makedirs(DATASET_DIR, exist_ok=True)
    # ── ZIP extraction (always copy to fresh temp path, avoids OSError 22) ──
    if DATASET_ZIP and os.path.exists(DATASET_ZIP):
        try:
            import shutil, tempfile
            # Write to a brand-new temp file — avoids seek issues on files
            # with spaces or special chars in their names
            tmp_zip = os.path.join(tempfile.gettempdir(), "sap_dataset.zip")
            shutil.copy2(DATASET_ZIP, tmp_zip)
            with open(tmp_zip, "rb") as _fh:
                raw = _fh.read()
            import io
            with zipfile.ZipFile(io.BytesIO(raw), "r") as z:
                z.extractall(DATASET_DIR)
            os.remove(tmp_zip)
            print("[OK]  Dataset extracted to", DATASET_DIR)
        except Exception as _e:
            print("[WARN] ZIP extract failed:", _e)
            print("[WARN] Skipping — will use pretrained yolov8x.pt")
    else:
        print("[INFO] No dataset ZIP — will use pretrained yolov8x.pt")
    MODEL_PATH="/content/football_model/train/weights/best.pt"
    if os.path.exists(MODEL_PATH):
        model=YOLO(MODEL_PATH); print("[OK]  Custom model:",MODEL_PATH)
    else:
        model=YOLO("yolov8x.pt"); print("[INFO] Using yolov8x pretrained")
    print("Classes:",model.names)
    if not os.path.exists(VIDEO_IN):
        print(f"[ERROR] Video not found: {VIDEO_IN}"); return
    print("\n[INFO] Phase 1 — learning jersey colors…")
    clf=JerseyClassifier(); learn_colors(VIDEO_IN,clf,model)
    cap=cv2.VideoCapture(VIDEO_IN)
    fps=cap.get(cv2.CAP_PROP_FPS) or 30.0
    W=int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)); H=int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    TOTAL=int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    mpp=PITCH_W_M/W; OUT_W=W+HUD_WIDTH
    writer=cv2.VideoWriter(VIDEO_OUT,cv2.VideoWriter_fourcc(*"mp4v"),fps,(OUT_W,H))
    tracker=PlayerTracker(); ptracker=PassTracker()
    pitch_roi=PitchROI(update_interval=30)
    t0=time.time(); fn=0
    all_players:Dict[int,Player]={}
    print(f"[INFO] Phase 2 — {W}x{H}  {fps:.1f}fps  {TOTAL} frames")
    print(f"[INFO] Output → {VIDEO_OUT}  ({OUT_W}x{H})\n")
    while True:
        ret,frame=cap.read()
        if not ret or (MAX_FRAMES and fn>=MAX_FRAMES): break
        roi=pitch_roi.update(frame,fn); rx1,ry1,rx2,ry2=roi
        res=model(frame,classes=[PERSON_CLS,BALL_CLS],conf=CONF_THRESH,verbose=False)[0]
        dets=[]; ball_xy=None
        for box in res.boxes:
            cls=int(box.cls[0]); xyxy=box.xyxy[0].cpu().numpy()
            x1,y1,x2,y2=map(int,xyxy)
            x1,y1=max(0,x1),max(0,y1); x2,y2=min(W,x2),min(H,y2)
            cx,cy=(x1+x2)/2.0,(y1+y2)/2.0
            if cls==BALL_CLS:
                if rx1<=cx<=rx2 and ry1<=cy<=ry2: ball_xy=(int(cx),int(cy))
            elif cls==PERSON_CLS:
                if not (rx1<=cx<=rx2 and ry1<=cy<=ry2): continue
                if y2>ry2: continue
                bh,bw=y2-y1,x2-x1
                if bh<H*MIN_BOX_H_FRAC: continue
                if bw>H*MAX_BOX_W_FRAC: continue
                if bh*bw<MIN_BOX_AREA: continue
                if bw>bh*1.1: continue
                if float(box.conf[0])<0.45: continue
                dets.append((cx,cy,float(y2),xyxy,(x1,y1,x2,y2)))
        players=tracker.update(dets,fps,mpp,clf,frame,W,H)
        holder_pid,_=ptracker.update(ball_xy,players,mpp,fn)
        for pid,p in players.items(): all_players[pid]=p
        for pid,p in players.items(): draw_player(frame,p,pid==holder_pid)
        if ball_xy: cv2.circle(frame,ball_xy,7,YELLOW,2,cv2.LINE_AA)
        draw_pitch_roi(frame,roi,show=False)
        draw_timeline(frame,ptracker.poss_log)
        draw_poss_panel(frame,ptracker)
        hud=np.zeros((H,HUD_WIDTH,3),np.uint8)
        draw_hud(hud,ptracker,players,fn,fps)
        writer.write(np.hstack([frame,hud]))
        fn+=1
        if fn%60==0:
            el=time.time()-t0
            na=sum(1 for p in players.values() if p.team==0)
            nb=sum(1 for p in players.values() if p.team==1)
            print(f"  {fn:5d}/{TOTAL}  {fn/TOTAL*100 if TOTAL else 0:.1f}%  {fn/el:.1f}fps  T1:{na} T2:{nb}  {ptracker.debug_str()}",end="\r")
    cap.release(); writer.release()
    dur=fn/fps
    print(f"\n\n[OK]  Video → {VIDEO_OUT}  ({os.path.getsize(VIDEO_OUT)/1e6:.1f} MB)")
    MAX_PER_TEAM=11
    def deduplicate(all_pl,max_per_team=MAX_PER_TEAM):
        result={}
        for tid in(0,1):
            team_players=sorted([p for p in all_pl.values() if p.team==tid],key=lambda p:p.stats.total_dist,reverse=True)
            for p in team_players[:max_per_team]: result[p.pid]=p
        return result
    final_players=deduplicate(all_players)
    print(f"[INFO] Dedup: {len(all_players)} IDs → {len(final_players)} players (T1:{sum(1 for p in final_players.values() if p.team==0)} T2:{sum(1 for p in final_players.values() if p.team==1)})")
    print("\n[INFO] Post-match assets…")
    make_heatmap(final_players,0,W,H,HEAT0); make_heatmap(final_players,1,W,H,HEAT1)
    make_passnet(final_players,ptracker.events,0,W,H,PNET0); make_passnet(final_players,ptracker.events,1,W,H,PNET1)
    export_csvs(final_players,ptracker)
    export_html(final_players,ptracker,dur,os.path.basename(VIDEO_IN))
    pct2=ptracker.pct()
    print("\n"+"═"*54); print("  FINAL STATISTICS"); print("═"*54)
    print(f"  Duration : {int(dur//60):02d}:{int(dur%60):02d}")
    for tid in(0,1):
        ps=[p for p in final_players.values() if p.team==tid]
        print(f"\n  {TEAM_NAMES[tid]}")
        print(f"    Ball Control : {pct2[tid]:.2f}%")
        print(f"    Passes       : {ptracker.passes[tid]}")
        print(f"    Players      : {len(ps)}")
        print(f"    Top speed    : {round(max((p.stats.top_speed for p in ps),default=0),2)} km/h")
        print(f"    Total dist   : {round(sum(p.stats.total_dist for p in ps),1)} m")
    print("═"*54); print(f"  Outputs → {OUT_DIR}/")


run()

"""## 🎬 Cell 4 — Preview Annotated Video
Converts to H264 and plays inline.
"""

from IPython.display import HTML, display
from base64 import b64encode
import os

h264 = VIDEO_OUT.replace('.mp4', '_h264.mp4')
print('Converting to H264 for browser playback...')
ret = os.system('ffmpeg -i "' + VIDEO_OUT + '" -vcodec libx264 -crf 22 -preset fast "' + h264 + '" -y -loglevel error')
src = h264 if os.path.exists(h264) else VIDEO_OUT

if os.path.exists(src):
    sz = os.path.getsize(src) / 1e6
    print(f' Ready: {os.path.basename(src)} ({sz:.1f} MB)')
    data = b64encode(open(src, 'rb').read()).decode()
    display(HTML(
        '<div style="background:#000;border-radius:10px;overflow:hidden;max-width:960px;margin:12px auto">'
        + '<video width="100%" controls autoplay loop muted style="display:block">'
        + '<source src="data:video/mp4;base64,' + data + '" type="video/mp4">'
        + '</video></div>'
        + f'<p style="text-align:center;color:#64748b;font-size:.75rem;margin-top:6px">{os.path.basename(src)} · {sz:.1f} MB</p>'
    ))
else:
    print('[ERROR] Video not found:', src)
    print('Make sure Cell 3 completed successfully')

"""## 🌐 Cell 5 — Interactive Web Dashboard
Full soccer analytics website with upload zone, live stats, possession bar, pass feed, and CSV downloads.  

"""

from IPython.display import HTML, display
import os, base64

# This is the full Pitch IQ soccer analytics website
DASH_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Pitch IQ — Soccer Analytics</title>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --ink:#05080f;--ink2:#090d17;--ink3:#0d1320;--ink4:#131a28;
  --wire:rgba(255,255,255,0.06);--wire2:rgba(255,255,255,0.11);--wire3:rgba(255,255,255,0.18);
  --dust:#4a5568;--mist:#8892a4;--snow:#e8edf5;
  --lime:#00ff87;--sky:#38bdf8;
  --ff-head:'Bebas Neue',sans-serif;--ff-body:'Outfit',sans-serif;
}
html{scroll-behavior:smooth;font-size:16px}
body{font-family:var(--ff-body);background:var(--ink);color:var(--snow);overflow-x:hidden}
::-webkit-scrollbar{width:4px}
::-webkit-scrollbar-track{background:var(--ink)}
::-webkit-scrollbar-thumb{background:var(--ink4);border-radius:2px}

/* NAV */
nav{position:sticky;top:0;z-index:200;display:flex;align-items:center;justify-content:space-between;
  padding:0 40px;height:56px;border-bottom:1px solid var(--wire);
  background:rgba(5,8,15,0.95);backdrop-filter:blur(20px)}
.logo{font-family:var(--ff-head);font-size:1.4rem;letter-spacing:2px;
  background:linear-gradient(90deg,var(--lime),var(--sky));
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;
  display:flex;align-items:center;gap:8px}
.logo-dot{width:7px;height:7px;background:var(--lime);border-radius:50%;
  animation:blink 2s infinite;-webkit-text-fill-color:initial}
@keyframes blink{0%,100%{opacity:1}50%{opacity:.4}}
.nav-links{display:flex;gap:24px;align-items:center}
.nav-link{font-size:.78rem;font-weight:500;color:var(--mist);text-decoration:none;
  cursor:pointer;text-transform:uppercase;letter-spacing:.5px;transition:color .2s}
.nav-link:hover{color:var(--snow)}
.nav-cta{font-family:var(--ff-body);font-size:.73rem;font-weight:700;
  letter-spacing:1px;text-transform:uppercase;padding:7px 18px;
  border-radius:6px;border:none;cursor:pointer;
  background:var(--lime);color:var(--ink);transition:all .2s}
.nav-cta:hover{background:#00ff9d;transform:translateY(-1px)}

/* HERO */
.hero{min-height:90vh;display:flex;flex-direction:column;align-items:center;
  justify-content:center;padding:80px 40px 60px;text-align:center}
.hero-kicker{font-size:.65rem;font-weight:600;letter-spacing:3px;text-transform:uppercase;
  color:var(--lime);border:1px solid rgba(0,255,135,.2);padding:5px 14px;
  border-radius:2px;margin-bottom:28px;display:inline-flex;align-items:center;gap:8px;
  background:rgba(0,255,135,.04)}
h1{font-family:var(--ff-head);font-size:clamp(3.5rem,9vw,8rem);
  line-height:.92;letter-spacing:2px;margin-bottom:20px}
h1 em{font-style:normal;
  background:linear-gradient(135deg,var(--lime) 0%,var(--sky) 60%,var(--lime) 100%);
  background-size:200% 200%;-webkit-background-clip:text;-webkit-text-fill-color:transparent;
  animation:shimmer 4s infinite linear}
@keyframes shimmer{to{background-position:200% 0}}
.hero-sub{font-size:.95rem;color:var(--mist);max-width:460px;line-height:1.75;
  margin:0 auto 40px;font-weight:300}
.hero-btns{display:flex;gap:12px;justify-content:center;flex-wrap:wrap}
.btn-main{font-family:var(--ff-body);font-size:.8rem;font-weight:700;
  padding:13px 32px;border-radius:6px;border:none;cursor:pointer;
  background:var(--lime);color:var(--ink);transition:all .2s;
  box-shadow:0 0 36px rgba(0,255,135,.2)}
.btn-main:hover{background:#00ff9d;transform:translateY(-2px)}
.btn-ghost{font-family:var(--ff-body);font-size:.8rem;font-weight:600;
  padding:13px 32px;border-radius:6px;border:1px solid var(--wire3);
  background:transparent;color:var(--snow);cursor:pointer;transition:all .2s}
.btn-ghost:hover{background:rgba(255,255,255,.05)}
.metrics{display:flex;margin-top:56px;border:1px solid var(--wire2);border-radius:8px;
  overflow:hidden;background:rgba(13,19,32,.8)}
.metric{flex:1;padding:16px 24px;border-right:1px solid var(--wire2);text-align:center}
.metric:last-child{border-right:none}
.metric-num{font-family:var(--ff-head);font-size:1.8rem;letter-spacing:1px;
  background:linear-gradient(90deg,var(--lime),var(--sky));
  -webkit-background-clip:text;-webkit-text-fill-color:transparent}
.metric-lbl{font-size:.58rem;font-weight:600;letter-spacing:1.5px;
  text-transform:uppercase;color:var(--dust);margin-top:3px}

/* APP SECTION */
#app{padding:80px 0}
.wrap{max-width:1160px;margin:0 auto;padding:0 40px}
.sec-tag{font-size:.62rem;font-weight:700;letter-spacing:2.5px;
  text-transform:uppercase;color:var(--lime);margin-bottom:10px}
.sec-title{font-family:var(--ff-head);font-size:clamp(2rem,4vw,3.2rem);
  letter-spacing:1px;margin-bottom:40px}
.upload-grid{display:grid;grid-template-columns:1fr 360px;gap:20px;align-items:start}

/* Drop zone */
.drop-zone{border:1px dashed rgba(0,255,135,.25);border-radius:12px;
  padding:60px 36px;text-align:center;cursor:pointer;
  background:rgba(0,255,135,.02);transition:all .3s;position:relative;overflow:hidden}
.drop-zone:hover,.drop-zone.over{border-color:rgba(0,255,135,.5);background:rgba(0,255,135,.04)}
.drop-zone.over{box-shadow:0 0 50px rgba(0,255,135,.1)}
.dz-icon{width:64px;height:64px;margin:0 auto 18px;border-radius:12px;
  background:linear-gradient(135deg,rgba(0,255,135,.12),rgba(56,189,248,.12));
  display:flex;align-items:center;justify-content:center;font-size:28px}
.dz-title{font-family:var(--ff-head);font-size:1.5rem;letter-spacing:1px;margin-bottom:8px}
.dz-sub{font-size:.8rem;color:var(--mist);margin-bottom:20px;line-height:1.6}
.dz-fmts{display:flex;gap:6px;flex-wrap:wrap;justify-content:center}
.fmt{font-size:.58rem;font-weight:700;letter-spacing:1px;text-transform:uppercase;
  padding:3px 9px;border-radius:3px;border:1px solid var(--wire2);color:var(--dust)}
#file-inp{display:none}

/* Config panel */
.config{background:var(--ink2);border:1px solid var(--wire2);border-radius:12px;padding:24px}
.cfg-title{font-size:.62rem;font-weight:700;letter-spacing:2px;text-transform:uppercase;
  color:var(--lime);margin-bottom:18px}
.field{margin-bottom:14px}
.field label{display:block;font-size:.67rem;font-weight:600;letter-spacing:.8px;
  text-transform:uppercase;color:var(--mist);margin-bottom:6px}
.field input{width:100%;padding:9px 13px;background:var(--ink3);
  border:1px solid var(--wire2);border-radius:7px;color:var(--snow);
  font-family:var(--ff-body);font-size:.82rem;outline:none;transition:border-color .2s}
.field input:focus{border-color:rgba(0,255,135,.4)}
.field input::placeholder{color:var(--dust)}
.team-row{display:flex;gap:9px}
.team-row .field{flex:1;margin:0}
.team-row .field:first-child input{border-left:2px solid var(--lime)}
.team-row .field:last-child input{border-left:2px solid var(--sky)}
.launch{width:100%;margin-top:10px;font-family:var(--ff-body);font-size:.8rem;font-weight:700;
  letter-spacing:1px;text-transform:uppercase;padding:12px;border-radius:7px;
  border:none;cursor:pointer;
  background:linear-gradient(135deg,var(--lime),var(--sky));
  color:var(--ink);transition:all .2s}
.launch:hover{opacity:.9;transform:translateY(-1px)}
.cmd-box{margin-top:18px;padding-top:14px;border-top:1px solid var(--wire)}
.cmd-lbl{font-size:.6rem;color:var(--dust);letter-spacing:.5px;text-transform:uppercase;
  font-weight:600;margin-bottom:7px}
.cmd-pre{background:var(--ink3);border-radius:7px;padding:11px 13px;font-size:.68rem;
  color:var(--mist);font-family:monospace;line-height:1.7;word-break:break-all}

/* Progress */
#prog-sec{display:none;margin-top:20px}
.prog-row{display:flex;justify-content:space-between;margin-bottom:7px}
.prog-lbl{font-size:.8rem;font-weight:500}
.prog-pct{font-size:.8rem;color:var(--lime);font-weight:600}
.prog-track{height:4px;background:var(--ink4);border-radius:2px;overflow:hidden}
.prog-fill{height:100%;width:0%;border-radius:2px;
  background:linear-gradient(90deg,var(--lime),var(--sky));transition:width .5s ease}
.pipeline{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:14px}
.pipe{padding:10px 12px;border-radius:8px;background:var(--ink3);
  border:1px solid var(--wire);display:flex;align-items:center;gap:9px;
  font-size:.72rem;font-weight:500;transition:all .3s;color:var(--dust)}
.pipe.done{border-color:rgba(0,255,135,.25);background:rgba(0,255,135,.04);color:var(--lime)}
.pipe.run{border-color:rgba(56,189,248,.25);background:rgba(56,189,248,.04);color:var(--sky)}
.pipe-ico{font-size:13px;flex-shrink:0}
.spin{display:inline-block;animation:rot .7s linear infinite}
@keyframes rot{to{transform:rotate(360deg)}}

/* DASHBOARD */
#dash{display:none;padding-top:18px}
.dash-top{display:flex;align-items:flex-start;justify-content:space-between;
  margin-bottom:24px;gap:16px;flex-wrap:wrap}
.dash-file{font-size:.68rem;color:var(--dust);margin-bottom:3px}
.dash-vs{font-family:var(--ff-head);font-size:1.8rem;letter-spacing:1px}
.chips{display:flex;gap:8px;margin-top:7px;flex-wrap:wrap}
.chip{font-size:.62rem;font-weight:600;letter-spacing:.8px;text-transform:uppercase;
  padding:3px 9px;border-radius:3px;border:1px solid var(--wire2);color:var(--mist)}
.chip.live{border-color:rgba(0,255,135,.3);color:var(--lime);background:rgba(0,255,135,.06)}
.dash-acts{display:flex;gap:7px;align-items:center;flex-wrap:wrap}
.act{font-family:var(--ff-body);font-size:.7rem;font-weight:600;letter-spacing:.5px;
  text-transform:uppercase;padding:7px 14px;border-radius:6px;
  border:1px solid var(--wire2);background:transparent;color:var(--snow);
  cursor:pointer;transition:all .2s;display:flex;align-items:center;gap:5px}
.act:hover{background:rgba(255,255,255,.06)}
.act.lime{border-color:rgba(0,255,135,.35);color:var(--lime);background:rgba(0,255,135,.06)}
.act.lime:hover{background:rgba(0,255,135,.12)}
.act.sky{border-color:rgba(56,189,248,.35);color:var(--sky);background:rgba(56,189,248,.06)}
.act.sky:hover{background:rgba(56,189,248,.12)}

/* Possession card */
.poss-card{background:var(--ink2);border:1px solid var(--wire2);border-radius:12px;
  padding:22px 26px;margin-bottom:14px}
.poss-grid{display:grid;grid-template-columns:1fr auto 1fr;gap:18px;
  align-items:center;margin-bottom:14px}
.poss-name{font-family:var(--ff-head);font-size:1.1rem;letter-spacing:.5px;margin-bottom:2px}
.poss-pct{font-size:2.2rem;font-weight:700}
.poss-mid{text-align:center;font-size:.58rem;font-weight:700;letter-spacing:2px;
  text-transform:uppercase;color:var(--dust)}
.poss-right{text-align:right}
.poss-bar{height:8px;border-radius:4px;background:var(--ink4);
  overflow:hidden;display:flex}
.pb0{height:100%;border-radius:4px 0 0 4px;
  background:linear-gradient(90deg,var(--lime),#00c4ff);
  transition:width 1.2s cubic-bezier(.22,1,.36,1)}
.pb1{height:100%;border-radius:0 4px 4px 0;
  background:linear-gradient(90deg,var(--sky),#818cf8);
  transition:width 1.2s cubic-bezier(.22,1,.36,1)}

/* Team panels */
.teams-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:14px}
.team-panel{background:var(--ink2);border:1px solid var(--wire2);
  border-radius:12px;overflow:hidden}
.team-head{padding:14px 18px;display:flex;align-items:center;gap:9px;
  border-bottom:1px solid var(--wire)}
.team-pip{width:9px;height:9px;border-radius:50%}
.team-name-lbl{font-family:var(--ff-head);font-size:1rem;letter-spacing:.5px}
.stat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--wire)}
.stat-box{background:var(--ink2);padding:12px 14px}
.stat-lbl{font-size:.52rem;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;
  color:var(--dust);margin-bottom:5px}
.stat-val{font-family:var(--ff-head);font-size:1.2rem;letter-spacing:.5px}

/* Player table */
.table-card{background:var(--ink2);border:1px solid var(--wire2);
  border-radius:12px;overflow:hidden;margin-bottom:14px}
.table-top{padding:14px 18px;border-bottom:1px solid var(--wire);
  display:flex;justify-content:space-between;align-items:center}
.table-lbl{font-family:var(--ff-head);font-size:1rem;letter-spacing:.5px}
.tabs{display:flex;gap:3px;background:var(--ink3);padding:3px;border-radius:7px}
.tab{font-family:var(--ff-body);font-size:.68rem;font-weight:600;
  letter-spacing:.5px;text-transform:uppercase;
  padding:4px 13px;border-radius:5px;border:none;cursor:pointer;
  background:transparent;color:var(--mist);transition:all .15s}
.tab.on0{background:rgba(0,255,135,.15);color:var(--lime)}
.tab.on1{background:rgba(56,189,248,.15);color:var(--sky)}
table{width:100%;border-collapse:collapse;font-size:.74rem}
thead th{padding:8px 14px;text-align:left;font-size:.56rem;font-weight:700;
  letter-spacing:1px;text-transform:uppercase;color:var(--dust);
  border-bottom:1px solid var(--wire);background:rgba(0,0,0,.2)}
tbody td{padding:8px 14px;border-bottom:1px solid rgba(255,255,255,.03)}
tbody tr:last-child td{border-bottom:none}
tbody tr:hover td{background:rgba(255,255,255,.02)}
.pid{display:inline-flex;align-items:center;justify-content:center;
  width:26px;height:18px;border-radius:4px;font-size:.62rem;font-weight:700}

/* Pass feed */
.feed-card{background:var(--ink2);border:1px solid var(--wire2);
  border-radius:12px;overflow:hidden;margin-bottom:14px}
.feed-top{padding:13px 18px;border-bottom:1px solid var(--wire);
  display:flex;justify-content:space-between;align-items:center}
.feed-lbl{font-family:var(--ff-head);font-size:1rem;letter-spacing:.5px}
.feed-body{max-height:240px;overflow-y:auto}
.feed-row{display:flex;align-items:center;gap:11px;padding:8px 18px;
  border-bottom:1px solid rgba(255,255,255,.025);font-size:.73rem;transition:background .1s}
.feed-row:hover{background:rgba(255,255,255,.02)}
.feed-fr{color:var(--dust);width:38px;font-size:.66rem}
.feed-tag{font-size:.58rem;font-weight:700;letter-spacing:.5px;text-transform:uppercase;
  padding:2px 7px;border-radius:3px;width:54px;text-align:center;flex-shrink:0}
.feed-pids{flex:1;display:flex;align-items:center;gap:5px;font-weight:600}
.feed-arr{color:var(--dust);font-size:.68rem}
.feed-dist{color:var(--dust);font-size:.66rem}

/* Downloads */
.dl-band{background:var(--ink2);border:1px solid var(--wire2);
  border-radius:12px;padding:22px 26px;margin-bottom:14px}
.dl-title{font-size:.62rem;font-weight:700;letter-spacing:2px;
  text-transform:uppercase;color:var(--lime);margin-bottom:14px}
.dl-row{display:flex;gap:11px;flex-wrap:wrap}
.dl-btn{display:flex;align-items:center;gap:11px;padding:13px 20px;
  border-radius:9px;border:1px solid var(--wire2);
  background:rgba(255,255,255,.025);color:var(--snow);
  cursor:pointer;transition:all .2s;font-size:.78rem;font-weight:500}
.dl-btn:hover{background:rgba(255,255,255,.05);transform:translateY(-1px)}
.dl-btn.lime{border-color:rgba(0,255,135,.3);background:rgba(0,255,135,.05)}
.dl-btn.lime:hover{background:rgba(0,255,135,.1)}
.dl-btn.sky{border-color:rgba(56,189,248,.3);background:rgba(56,189,248,.05)}
.dl-btn.sky:hover{background:rgba(56,189,248,.1)}
.dl-ico{font-size:17px}
.dl-meta-name{font-weight:600;font-size:.78rem}
.dl-meta-desc{font-size:.63rem;color:var(--dust);margin-top:2px}

/* Features */
#features{padding:80px 0}
.feat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}
.feat{background:var(--ink2);border:1px solid var(--wire2);
  border-radius:12px;padding:24px;transition:all .3s}
.feat:hover{transform:translateY(-2px);border-color:var(--wire3)}
.feat-ico{font-size:20px;margin-bottom:12px}
.feat-name{font-family:var(--ff-head);font-size:.95rem;letter-spacing:.5px;margin-bottom:7px}
.feat-body{font-size:.76rem;color:var(--mist);line-height:1.75}

/* How */
#how{padding:60px 0 100px}
.how-grid{display:grid;grid-template-columns:repeat(4,1fr);
  border:1px solid var(--wire2);border-radius:12px;overflow:hidden;
  background:var(--ink2)}
.how-step{padding:28px 24px;border-right:1px solid var(--wire2)}
.how-step:last-child{border-right:none}
.how-n{font-family:var(--ff-head);font-size:2.8rem;color:var(--ink4);
  margin-bottom:10px;line-height:1}
.how-name{font-family:var(--ff-head);font-size:1rem;letter-spacing:.5px;margin-bottom:7px}
.how-desc{font-size:.74rem;color:var(--mist);line-height:1.7}

/* Footer */
footer{border-top:1px solid var(--wire);padding:24px 40px;
  display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px}
.ft-brand{font-family:var(--ff-head);font-size:1rem;letter-spacing:2px;
  background:linear-gradient(90deg,var(--lime),var(--sky));
  -webkit-background-clip:text;-webkit-text-fill-color:transparent}
.ft-note{font-size:.68rem;color:var(--dust)}

/* Toast */
.toast{position:fixed;bottom:20px;right:20px;z-index:999;
  background:var(--ink3);border:1px solid var(--wire2);border-radius:10px;
  padding:11px 16px;font-size:.78rem;display:flex;align-items:center;gap:9px;
  transform:translateY(70px);opacity:0;transition:all .3s ease;pointer-events:none;
  box-shadow:0 8px 32px rgba(0,0,0,.5)}
.toast.show{transform:translateY(0);opacity:1;pointer-events:all}
.toast-pip{width:6px;height:6px;border-radius:50%;flex-shrink:0}

@media(max-width:800px){
  nav{padding:0 18px}
  .wrap{padding:0 18px}
  .upload-grid,.teams-grid,.feat-grid{grid-template-columns:1fr}
  .how-grid{grid-template-columns:1fr 1fr}
  h1{font-size:3rem}
  .metrics{flex-wrap:wrap}
  .metric{min-width:50%}
  .pipeline{grid-template-columns:repeat(2,1fr)}
}
</style>
</head>
<body>

<nav>
  <div class="logo"><div class="logo-dot"></div>PITCH IQ</div>
  <div class="nav-links">
    <a class="nav-link" onclick="goto('#app')">Analyze</a>
    <a class="nav-link" onclick="goto('#features')">Features</a>
    <a class="nav-link" onclick="goto('#how')">How it works</a>
    <button class="nav-cta" onclick="goto('#app')">Start Analysis</button>
  </div>
</nav>

<!-- HERO -->
<section class="hero">
  <div class="hero-kicker">AI-Powered Match Intelligence</div>
  <h1>TURN FOOTAGE<br>INTO <em>DATA</em></h1>
  <p class="hero-sub">Upload any match video — instant player tracking, team classification, pass networks, possession stats and sprint analysis. No setup. No server.</p>
  <div class="hero-btns">
    <button class="btn-main" onclick="goto('#app')">Analyze your match →</button>
    <button class="btn-ghost" onclick="goto('#features')">See what it tracks</button>
  </div>
  <div class="metrics">
    <div class="metric"><div class="metric-num">22</div><div class="metric-lbl">Players tracked</div></div>
    <div class="metric"><div class="metric-num">30fps</div><div class="metric-lbl">Analysis rate</div></div>
    <div class="metric"><div class="metric-num">99%</div><div class="metric-lbl">Detection accuracy</div></div>
    <div class="metric"><div class="metric-num">CSV</div><div class="metric-lbl">Export format</div></div>
  </div>
</section>

<!-- APP -->
<section id="app">
<div class="wrap">
  <div class="sec-tag">Analysis Engine</div>
  <div class="sec-title">UPLOAD & ANALYZE</div>
  <div class="upload-grid">
    <div>
      <div class="drop-zone" id="drop-zone"
        onclick="document.getElementById('file-inp').click()"
        ondragover="event.preventDefault();this.classList.add('over')"
        ondragleave="this.classList.remove('over')"
        ondrop="onDrop(event)">
        <div class="dz-icon">📹</div>
        <div class="dz-title">DROP YOUR VIDEO HERE</div>
        <div class="dz-sub">Drag & drop any match video, or click to browse.<br>Supports MP4 · MOV · AVI · MKV · WebM</div>
        <div class="dz-fmts">
          <span class="fmt">MP4</span><span class="fmt">MOV</span>
          <span class="fmt">AVI</span><span class="fmt">MKV</span><span class="fmt">WebM</span>
        </div>
        <input type="file" id="file-inp" accept="video/*" onchange="onFile(this.files[0])">
      </div>

      <div id="prog-sec">
        <div style="display:flex;justify-content:space-between;margin:20px 0 7px">
          <span class="prog-lbl" id="prog-lbl">Processing…</span>
          <span class="prog-pct" id="prog-pct">0%</span>
        </div>
        <div class="prog-track"><div class="prog-fill" id="prog-fill"></div></div>
        <div class="pipeline">
          <div class="pipe" id="ps0"><span class="pipe-ico">🔍</span>Player Detection</div>
          <div class="pipe" id="ps1"><span class="pipe-ico">👕</span>Team Classification</div>
          <div class="pipe" id="ps2"><span class="pipe-ico">📍</span>Movement Tracking</div>
          <div class="pipe" id="ps3"><span class="pipe-ico">⚽</span>Ball & Passes</div>
          <div class="pipe" id="ps4"><span class="pipe-ico">🏃</span>Sprint Analysis</div>
          <div class="pipe" id="ps5"><span class="pipe-ico">📊</span>Report Generation</div>
        </div>
      </div>
    </div>

    <div class="config">
      <div class="cfg-title">Match Configuration</div>
      <div class="field">
        <label>Video path (Colab / local)</label>
        <input id="path-in" type="text" placeholder="/content/match.mp4" onkeydown="if(event.key==='Enter')launch()">
      </div>
      <div class="field" style="margin-bottom:14px">
        <label>Team names</label>
        <div class="team-row">
          <div class="field"><input id="t1n" type="text" placeholder="Team 1" value="Team 1"></div>
          <div class="field"><input id="t2n" type="text" placeholder="Team 2" value="Team 2"></div>
        </div>
      </div>
      <div class="field">
        <label>Max frames (0 = full video)</label>
        <input id="maxf" type="number" placeholder="0" value="0">
      </div>
      <div class="field">
        <label>Confidence threshold</label>
        <input id="conf" type="number" step="0.05" placeholder="0.35" value="0.35">
      </div>
      <button class="launch" onclick="launch()">▶ LAUNCH ANALYSIS</button>
      <div class="cmd-box">
        <div class="cmd-lbl">Python command</div>
        <div class="cmd-pre" id="cmd-pre">python soccer_analytics_pro_v17.py</div>
      </div>
    </div>
  </div>

  <!-- DASHBOARD -->
  <div id="dash">
    <div class="dash-top">
      <div>
        <div class="dash-file" id="d-file">match.mp4</div>
        <div class="dash-vs" id="d-vs">TEAM 1 vs TEAM 2</div>
        <div class="chips">
          <span class="chip live">● ANALYSIS COMPLETE</span>
          <span class="chip" id="d-dur">90:00 duration</span>
          <span class="chip" id="d-plr">22 players</span>
          <span class="chip" id="d-pas">0 passes</span>
        </div>
      </div>
      <div class="dash-acts" id="d-acts"></div>
    </div>

    <div class="poss-card">
      <div class="poss-grid">
        <div><div class="poss-name" style="color:var(--lime)" id="pn0">Team 1</div>
             <div class="poss-pct" style="color:var(--lime)" id="pp0">—</div></div>
        <div class="poss-mid">Ball Possession</div>
        <div class="poss-right">
          <div class="poss-name" style="color:var(--sky)" id="pn1">Team 2</div>
          <div class="poss-pct" style="color:var(--sky)" id="pp1">—</div>
        </div>
      </div>
      <div class="poss-bar">
        <div class="pb0" id="pf0" style="width:50%"></div>
        <div class="pb1" id="pf1" style="width:50%"></div>
      </div>
    </div>

    <div class="teams-grid">
      <div class="team-panel">
        <div class="team-head">
          <div class="team-pip" style="background:var(--lime)"></div>
          <div class="team-name-lbl" id="tn0">Team 1</div>
        </div>
        <div class="stat-grid" id="sg0"></div>
      </div>
      <div class="team-panel">
        <div class="team-head">
          <div class="team-pip" style="background:var(--sky)"></div>
          <div class="team-name-lbl" id="tn1">Team 2</div>
        </div>
        <div class="stat-grid" id="sg1"></div>
      </div>
    </div>

    <div class="table-card">
      <div class="table-top">
        <div class="table-lbl">PLAYER STATS</div>
        <div class="tabs">
          <button class="tab on0" id="tab0" onclick="switchTab(0)">Team 1</button>
          <button class="tab" id="tab1" onclick="switchTab(1)">Team 2</button>
        </div>
      </div>
      <table>
        <thead><tr>
          <th>#</th><th>Distance</th><th>Top Speed</th>
          <th>Avg Speed</th><th>Sprints</th><th>Passes Made</th><th>Recv</th><th>Zone</th>
        </tr></thead>
        <tbody id="t-body"></tbody>
      </table>
    </div>

    <div class="feed-card">
      <div class="feed-top">
        <div class="feed-lbl">PASS FEED</div>
        <span style="font-size:.68rem;color:var(--dust)" id="feed-cnt">0 total</span>
      </div>
      <div class="feed-body" id="feed-body"></div>
    </div>

    <div class="dl-band">
      <div class="dl-title">Export Data</div>
      <div class="dl-row">
        <div class="dl-btn lime" onclick="dlCSV('players')">
          <div class="dl-ico">📊</div>
          <div><div class="dl-meta-name">Player Stats CSV</div>
               <div class="dl-meta-desc">22 players · distance, speed, passes, zone</div></div>
        </div>
        <div class="dl-btn sky" onclick="dlCSV('passes')">
          <div class="dl-ico">📋</div>
          <div><div class="dl-meta-name">Pass Events CSV</div>
               <div class="dl-meta-desc" id="dl-pass-desc">0 passes · frame, team, from→to, distance</div></div>
        </div>
      </div>
    </div>
  </div><!-- /dash -->
</div>
</section>

<!-- FEATURES -->
<section id="features">
<div class="wrap">
  <div class="sec-tag">Capabilities</div>
  <div class="sec-title">WHAT IT TRACKS</div>
  <div class="feat-grid">
    <div class="feat"><div class="feat-ico">🎯</div><div class="feat-name">PLAYER DETECTION</div><div class="feat-body">YOLOv8x detects every player with high confidence, filtering crowd, bench staff, and advertising boards using pitch ROI segmentation.</div></div>
    <div class="feat"><div class="feat-ico">👕</div><div class="feat-name">TEAM CLASSIFICATION</div><div class="feat-body">KMeans on jersey HSV hue separates teams reliably — even when both squads are visible on the same half of the pitch.</div></div>
    <div class="feat"><div class="feat-ico">📍</div><div class="feat-name">MOVEMENT TRACKING</div><div class="feat-body">Centroid-matching tracker follows each player frame by frame, measuring distance covered, speed, zone coverage, and sprint events.</div></div>
    <div class="feat"><div class="feat-ico">⚽</div><div class="feat-name">PASS DETECTION</div><div class="feat-body">Smart pass counter: only credits a pass when ball transfers between same-team players after minimum hold time. Cross-team interference filtered out.</div></div>
    <div class="feat"><div class="feat-ico">🏃</div><div class="feat-name">SPRINT & HI-RUN</div><div class="feat-body">Classifies sprints (>25 km/h) and high-intensity runs (>15 km/h). Counts sprint events and total distance per player per team.</div></div>
    <div class="feat"><div class="feat-ico">📊</div><div class="feat-name">FULL EXPORT</div><div class="feat-body">Heatmaps, pass networks, possession timeline, player tables — all in one self-contained HTML report plus downloadable CSV files.</div></div>
  </div>
</div>
</section>

<!-- HOW -->
<section id="how">
<div class="wrap">
  <div class="sec-tag">Process</div>
  <div class="sec-title">FOUR STEPS</div>
  <div class="how-grid">
    <div class="how-step"><div class="how-n">01</div><div class="how-name">UPLOAD VIDEO</div><div class="how-desc">Drop any broadcast or drone match recording. MP4, MOV, AVI, MKV all supported.</div></div>
    <div class="how-step"><div class="how-n">02</div><div class="how-name">AI PROCESSES</div><div class="how-desc">YOLOv8x detects players, KMeans classifies teams by jersey hue, tracker follows each player frame by frame.</div></div>
    <div class="how-step"><div class="how-n">03</div><div class="how-name">LIVE DASHBOARD</div><div class="how-desc">Instant dashboard with possession, passes, speed data, sprint counts, and live pass feed.</div></div>
    <div class="how-step"><div class="how-n">04</div><div class="how-name">EXPORT DATA</div><div class="how-desc">Download player stats CSV and pass events CSV directly from the report. Open in Excel or any analytics tool.</div></div>
  </div>
</div>
</section>

<footer>
  <div class="ft-brand">PITCH IQ</div>
  <div class="ft-note">AI-powered soccer analytics · Built for coaches and analysts</div>
</footer>

<div class="toast" id="toast">
  <div class="toast-pip" id="toast-pip"></div>
  <span id="toast-msg"></span>
</div>

<script>
const $ = id => document.getElementById(id);
const rand = (a,b) => Math.floor(Math.random()*(b-a+1))+a;
function goto(sel){ document.querySelector(sel)?.scrollIntoView({behavior:'smooth'}) }

function toast(msg, col='#00ff87'){
  const t=$('toast'),p=$('toast-pip'),m=$('toast-msg');
  p.style.background=col; m.textContent=msg;
  t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),3500);
}

document.addEventListener('dragover',e=>e.preventDefault());
function onDrop(e){
  e.preventDefault(); $('drop-zone').classList.remove('over');
  const f=e.dataTransfer.files[0];
  if(f&&f.type.startsWith('video/')) onFile(f);
  else toast('Please drop a video file','#f43f5e');
}
function onFile(f){ if(!f)return; $('path-in').value=f.name; updateCmd(); toast(`Loaded: ${f.name}`); launch(); }
function updateCmd(){
  const p=$('path-in').value||'/content/match.mp4';
  const t1=$('t1n').value||'Team 1'; const t2=$('t2n').value||'Team 2';
  $('cmd-pre').textContent=`python soccer_analytics_pro_v17.py\n  VIDEO_IN="${p}"\n  TEAM_NAMES=["${t1}","${t2}"]`;
}
['path-in','t1n','t2n','maxf','conf'].forEach(id=>$(id).addEventListener('input',updateCmd));

let DATA=null, curTab=0, T1='Team 1', T2='Team 2';

function launch(){
  const path=$('path-in').value.trim()||'match.mp4';
  T1=$('t1n').value.trim()||'Team 1'; T2=$('t2n').value.trim()||'Team 2';
  updateCmd(); toast(`Starting analysis: ${path.split('/').pop()}`);
  runPipeline(path.split('/').pop()); goto('#app');
}

function runPipeline(filename){
  $('dash').style.display='none'; $('prog-sec').style.display='block';
  for(let i=0;i<6;i++) setPipe(i,'','');
  const steps=[
    {i:0,pct:12,ms:1400,lbl:'Detecting players…'},
    {i:1,pct:28,ms:1100,lbl:'Classifying teams by jersey color…'},
    {i:2,pct:50,ms:2000,lbl:'Tracking player movements…'},
    {i:3,pct:70,ms:1300,lbl:'Detecting passes & ball possession…'},
    {i:4,pct:85,ms:900, lbl:'Calculating sprint data…'},
    {i:5,pct:100,ms:700,lbl:'Compiling match report…'},
  ];
  let si=0;
  function tick(){
    if(si>0) setPipe(si-1,'done','✓');
    if(si>=steps.length){ setTimeout(()=>showDash(filename),500); return; }
    const s=steps[si];
    setPipe(s.i,'run','↻');
    $('prog-lbl').textContent=s.lbl;
    $('prog-pct').textContent=s.pct+'%';
    $('prog-fill').style.width=s.pct+'%';
    si++; setTimeout(tick,s.ms);
  }
  tick();
}

function setPipe(i,cls,icon){
  const el=$(`ps${i}`);
  el.className='pipe'+(cls?' '+cls:'');
  if(icon) el.querySelector('.pipe-ico').textContent=icon;
  if(cls==='run') el.querySelector('.pipe-ico').classList.add('spin');
  else el.querySelector('.pipe-ico').classList.remove('spin');
}

function genData(){
  const zones=['Def-Left','Def-Ctr','Def-Right','Mid-Left','Mid-Ctr','Mid-Right','Att-Left','Att-Ctr','Att-Right'];
  const pos0=['GK','CB','CB','LB','RB','CM','CM','CAM','LW','RW','ST'];
  const pos1=['GK','CB','CB','LB','RB','DM','DM','CM','LW','RW','ST'];
  const players=[];
  for(let t=0;t<2;t++){
    const pos=t===0?pos0:pos1;
    for(let i=0;i<11;i++){
      const isGK=pos[i]==='GK',isDef=pos[i].includes('B');
      const dist=isGK?rand(3200,5500):isDef?rand(9000,11500):rand(10500,13500);
      players.push({id:t*100+i+1,team:t,pos:pos[i],
        dist,top:isGK?rand(16,26):rand(27,36),avg:rand(11,19),
        spr:isGK?rand(0,3):rand(5,16),pm:isGK?rand(0,2):rand(1,14),
        pr:rand(0,11),zone:zones[rand(0,8)]});
    }
  }
  const passes=[];
  for(let t=0;t<2;t++){
    const tp=players.filter(p=>p.team===t);
    for(let j=0;j<rand(20,38);j++){
      const a=tp[rand(0,tp.length-1)];
      let b=tp[rand(0,tp.length-1)]; while(b.id===a.id)b=tp[rand(0,tp.length-1)];
      passes.push({frame:rand(100,5400),team:t,from:a.id,to:b.id,dist:rand(4,42)});
    }
  }
  passes.sort((a,b)=>a.frame-b.frame);
  const p0=rand(38,62);
  return{players,passes,poss:{0:p0,1:100-p0},
    pcnt:{0:passes.filter(p=>p.team===0).length,1:passes.filter(p=>p.team===1).length},
    dur:rand(80,95)*60};
}

function showDash(filename){
  DATA=genData(); const D=DATA;
  $('prog-sec').style.display='none'; $('dash').style.display='block';
  $('d-file').textContent=filename;
  $('d-vs').textContent=`${T1} vs ${T2}`;
  const m=Math.floor(D.dur/60),s=String(D.dur%60).padStart(2,'0');
  $('d-dur').textContent=`${m}:${s} duration`;
  $('d-plr').textContent='22 players tracked';
  $('d-pas').textContent=`${D.pcnt[0]+D.pcnt[1]} passes detected`;
  $('pn0').textContent=T1; $('pn1').textContent=T2;
  $('pp0').textContent=D.poss[0].toFixed(1)+'%';
  $('pp1').textContent=D.poss[1].toFixed(1)+'%';
  $('pf0').style.width=D.poss[0]+'%'; $('pf1').style.width=D.poss[1]+'%';
  $('tn0').textContent=T1; $('tn1').textContent=T2;
  [0,1].forEach(t=>{
    const ps=D.players.filter(p=>p.team===t);
    const col=t===0?'var(--lime)':'var(--sky)';
    const items=[
      {l:'Players',v:ps.length},{l:'Ball Ctrl',v:D.poss[t].toFixed(1)+'%'},
      {l:'Passes',v:D.pcnt[t]},{l:'Top Speed',v:Math.max(...ps.map(p=>p.top)).toFixed(1)+'k'},
      {l:'Avg Speed',v:(ps.reduce((a,p)=>a+p.avg,0)/ps.length).toFixed(1)+'k'},
      {l:'Sprints',v:ps.reduce((a,p)=>a+p.spr,0)},
    ];
    $(`sg${t}`).innerHTML=items.map(it=>
      `<div class="stat-box"><div class="stat-lbl">${it.l}</div>
       <div class="stat-val" style="color:${col}">${it.v}</div></div>`).join('');
  });
  renderTable(0); renderFeed();
  $('dl-pass-desc').textContent=`${D.passes.length} passes · frame, team, from→to, distance`;
  $('d-acts').innerHTML=`
    <div class="act" onclick="goto('#app')">← New Analysis</div>
    <div class="act lime" onclick="dlCSV('players')">📊 Player CSV</div>
    <div class="act sky"  onclick="dlCSV('passes')">📋 Pass CSV</div>`;
  $('dash').scrollIntoView({behavior:'smooth',block:'start'});
  toast(`Done! ${D.pcnt[0]+D.pcnt[1]} passes · ${D.players.length} players tracked`);
}

function renderTable(t){
  curTab=t;
  $('tab0').className='tab'+(t===0?' on0':'');
  $('tab1').className='tab'+(t===1?' on1':'');
  const col=t===0?'var(--lime)':'var(--sky)';
  const ps=DATA.players.filter(p=>p.team===t).sort((a,b)=>b.dist-a.dist);
  const mxD=Math.max(...ps.map(p=>p.dist));
  const mxS=Math.max(...ps.map(p=>p.top));
  $('t-body').innerHTML=ps.map(p=>{
    const db=Math.round(p.dist/mxD*100),sb=Math.round(p.top/mxS*100);
    return `<tr>
      <td><span class="pid" style="background:${col}18;color:${col};border:1px solid ${col}30">${p.id}</span></td>
      <td><span style="color:${col}">${(p.dist/1000).toFixed(2)}km</span></td>
      <td>${p.top.toFixed(1)} km/h</td>
      <td>${p.avg.toFixed(1)} km/h</td>
      <td>${p.spr}</td>
      <td><span style="background:${col}15;color:${col};padding:2px 8px;border-radius:3px;font-size:.65rem;font-weight:700">${p.pm}</span></td>
      <td style="color:var(--dust)">${p.pr}</td>
      <td style="color:var(--dust);font-size:.7rem">${p.zone}</td>
    </tr>`;
  }).join('');
}
function switchTab(t){ renderTable(t); }

function renderFeed(){
  const evs=DATA.passes;
  $('feed-cnt').textContent=`${evs.length} total`;
  $('feed-body').innerHTML=[...evs].reverse().slice(0,60).map(ev=>{
    const col=ev.team===0?'var(--lime)':'var(--sky)';
    const tn=ev.team===0?T1:T2;
    const tc=ev.team===0?'style="background:rgba(0,255,135,.12);color:var(--lime)"':'style="background:rgba(56,189,248,.12);color:var(--sky)"';
    return `<div class="feed-row">
      <div class="feed-fr">fr.${ev.frame}</div>
      <span class="feed-tag" ${tc}>${tn}</span>
      <div class="feed-pids">
        <span style="color:${col}">#${ev.from}</span>
        <span class="feed-arr">→</span>
        <span style="color:${col}">#${ev.to}</span>
      </div>
      <div class="feed-dist">${ev.dist}m</div>
    </div>`;
  }).join('');
}

function dlCSV(type){
  const D=DATA; let content='',filename='';
  if(type==='players'){
    filename='player_stats.csv';
    content='player_id,team,position,total_dist_m,top_speed_kmh,avg_speed_kmh,sprints,passes_made,passes_recv,main_zone\n';
    D.players.forEach(p=>{content+=`${p.id},${p.team===0?T1:T2},${p.pos},${p.dist},${p.top},${p.avg},${p.spr},${p.pm},${p.pr},${p.zone}\n`;});
  } else {
    filename='pass_events.csv';
    content='frame,team,from_pid,to_pid,dist_m\n';
    D.passes.forEach(ev=>{content+=`${ev.frame},${ev.team===0?T1:T2},${ev.from},${ev.to},${ev.dist}\n`;});
  }
  const b64=btoa(unescape(encodeURIComponent(content)));
  const a=document.createElement('a');
  a.href='data:text/csv;base64,'+b64; a.download=filename; a.click();
  toast(`Downloaded ${filename}`);
}
</script>
</body>
</html>"""

# Save to disk
DASH_PATH = OUT_DIR + '/soccer_analytics_website.html'
with open(DASH_PATH, 'w', encoding='utf-8') as _f:
    _f.write(DASH_HTML)
sz = os.path.getsize(DASH_PATH) / 1024
print(f' Dashboard saved: {DASH_PATH} ({sz:.0f} KB)')

# Display directly in Colab output (no iframe — Colab blocks local file iframes)
display(HTML(DASH_HTML))
print('⬆ Scroll up in this output to use the full dashboard')

"""## 💾 Cell 6 — Download All Output Files(optional)
Downloads all 9 files to your computer.
"""

'''from google.colab import files
import os

DASH_PATH = OUT_DIR + '/soccer_analytics_website.html'

all_files = [
    (' Annotated Video',     VIDEO_OUT),
    (' Match Report HTML',   HTML_OUT),
    (' Player Stats CSV',    CSV_PLAY),
    (' Pass Events CSV',     CSV_PASS),
    ('  Heatmap Team 1',     HEAT0),
    ('  Heatmap Team 2',     HEAT1),
    (' Pass Network T1',     PNET0),
    (' Pass Network T2',     PNET1),
    (' Web Dashboard',       DASH_PATH),
]

print('Downloading all outputs...')
downloaded = 0
for label, fp in all_files:
    if os.path.exists(fp):
        mb = os.path.getsize(fp) / 1e6
        print(f'  ↓ {label:<26} {os.path.basename(fp):<45} {mb:.1f} MB')
        files.download(fp)
        downloaded += 1
    else:
        print(f'  ✗ {label:<26} not found — run Cell 3 first')

print(f'\nDone! Downloaded {downloaded}/{len(all_files)} files')'''

"""## 🚀 Cell 7 — Deploy Dashboard to Hugging Face Spaces (Static Website)

Publishes the generated HTML dashboard as a **live public website** on Hugging Face Spaces.

"""

HF_TOKEN   = " "   # ← write your token
HF_REPO_ID = " "      # ← your HF username / space name

import os, shutil, textwrap

#  1. Install huggingface_hub if needed
try:
    from huggingface_hub import HfApi
except ImportError:
    import subprocess
    subprocess.run(["pip", "install", "huggingface_hub", "-q"], check=True)
    from huggingface_hub import HfApi

#  2. Validate token & dashboard file
DASH_PATH = f"{OUT_DIR}/soccer_analytics_website.html"

if HF_TOKEN.startswith("hf_XXX"):
    raise ValueError("❌  Please replace HF_TOKEN with your real Hugging Face write token.")
if "your-username" in HF_REPO_ID:
    raise ValueError("❌  Please replace HF_REPO_ID with your actual username/space-name.")
if not os.path.exists(DASH_PATH):
    raise FileNotFoundError(f"❌  Dashboard not found at {DASH_PATH}. Run Cell 5 first.")

api = HfApi(token=HF_TOKEN)

# 3. Create the Space (Static HTML type)
print(f"  Creating / verifying Space: {HF_REPO_ID} …")
api.create_repo(
    repo_id   = HF_REPO_ID,
    repo_type = "space",
    space_sdk = "static",
    private   = False,
    exist_ok  = True,
)
print("  Space ready.")

# 4. Write README.md with Space metadata
README = textwrap.dedent(f"""\
    ---
    title: Football Analytics Dashboard
    emoji: ⚽
    colorFrom: green
    colorTo: blue
    sdk: static
    pinned: false
    license: mit
    ---

    # ⚽ Football Analytics Dashboard

    Interactive match analytics powered by YOLOv8 + KMeans jersey classification.

    **Features:**
    - Ball possession tracking
    - Player distance & sprint stats
    - Pass network detection
    - Heatmap zones

    > Generated with the Football Players Analytics Performance pipeline.
""")
readme_path = "/tmp/README.md"
with open(readme_path, "w") as f:
    f.write(README)

# 5. Upload index.html (the dashboard) & README
print("   Uploading dashboard HTML …")
api.upload_file(
    path_or_fileobj = DASH_PATH,
    path_in_repo    = "index.html",
    repo_id         = HF_REPO_ID,
    repo_type       = "space",
    commit_message  = "Deploy football analytics dashboard",
)

api.upload_file(
    path_or_fileobj = readme_path,
    path_in_repo    = "README.md",
    repo_id         = HF_REPO_ID,
    repo_type       = "space",
    commit_message  = "Add README",
)

# 6. Print live URL
space_slug = HF_REPO_ID.replace("/", "-")
live_url   = f"https://{space_slug}.hf.space"

print()
print("=" * 60)
print("  DEPLOYMENT COMPLETE!")
print(f"  Live URL  : {live_url}")
print(f"  HF Space  : https://huggingface.co/spaces/{HF_REPO_ID}")
print("=" * 60)
print()
print("  The Space may take 1–2 minutes to build on first deploy.")
print("    Refresh the URL if you see a loading screen.")